import { useEffect, useState } from 'react';
import { CheckCircle2, Clock3, Edit3, Eye, LogOut, Save, ShieldCheck, UserRound, XCircle } from 'lucide-react';
import { useNavigate } from 'react-router-dom';
import { useApp } from '../context/AppContext';
import { supabase } from '../lib/supabase';

type AccountType = 'buyer' | 'seller' | 'both';
type Profile = { full_name: string; username?: string | null; email: string; phone?: string | null; role: 'user' | 'moderator' | 'admin'; is_verified: boolean; account_type: AccountType };
type UserListing = { id: string; title: string; price: number; status: 'draft' | 'active' | 'sold' | 'archived'; image_urls?: string[]; created_at: string; municipalities?: { name: string } | null; categories?: { name: string } | null };
const listingStatus: Record<UserListing['status'], { label: string; className: string; icon: typeof Clock3 }> = { draft: { label: 'قيد المراجعة', className: 'bg-amber-50 text-amber-700', icon: Clock3 }, active: { label: 'منشور', className: 'bg-emerald-50 text-emerald-700', icon: CheckCircle2 }, sold: { label: 'مباع', className: 'bg-blue-50 text-blue-700', icon: CheckCircle2 }, archived: { label: 'غير مقبول', className: 'bg-rose-50 text-rose-700', icon: XCircle } };

export function AccountPage() {
  const { session, notify, logout } = useApp(); const navigate = useNavigate();
  const [profile, setProfile] = useState<Profile | null>(null); const [listings, setListings] = useState<UserListing[]>([]); const [loading, setLoading] = useState(true); const [editing, setEditing] = useState(false); const [saving, setSaving] = useState(false);
  const [form, setForm] = useState({ full_name: '', username: '', phone: '', account_type: 'both' as AccountType });
  const load = async () => {
    if (!supabase || !session) { setLoading(false); return; }
    setLoading(true);
    const [profileResult, listingResult] = await Promise.all([
      supabase.from('profiles').select('full_name,username,email,phone,role,is_verified,account_type').eq('id', session.user.id).limit(1).maybeSingle(),
      supabase.from('listings').select('id,title,price,status,image_urls,created_at,municipalities(name),categories(name)').eq('seller_id', session.user.id).order('created_at', { ascending: false }).limit(100),
    ]);
    if (profileResult.error) notify(`تعذر تحميل الحساب: ${profileResult.error.message}`);
    const nextProfile = profileResult.data as Profile | null; setProfile(nextProfile);
    if (nextProfile) setForm({ full_name: nextProfile.full_name || '', username: nextProfile.username || '', phone: nextProfile.phone || '', account_type: nextProfile.account_type || 'both' });
    if (listingResult.error) notify(`تعذر تحميل الإعلانات: ${listingResult.error.message}`);
    setListings((listingResult.data || []).map((item: any) => ({ ...item, municipalities: Array.isArray(item.municipalities) ? item.municipalities[0] || null : item.municipalities, categories: Array.isArray(item.categories) ? item.categories[0] || null : item.categories })) as UserListing[]);
    setLoading(false);
  };
  useEffect(() => { void load(); }, [session]);
  const saveProfile = async () => {
    if (!supabase || !session || !profile) return;
    const fullName = form.full_name.trim(); const username = form.username.trim().toLowerCase();
    if (fullName.length < 2) return notify('أدخل الاسم الكامل بشكل صحيح.');
    if (username && !/^[a-z0-9_\-.]{3,30}$/.test(username)) return notify('اسم المستخدم يجب أن يكون 3–30 حرفاً إنجليزية أو أرقاماً أو _ أو -.');
    setSaving(true);
    const { data, error } = await supabase.from('profiles').update({ full_name: fullName, username: username || null, phone: form.phone.trim() || null, account_type: form.account_type }).eq('id', session.user.id).select('full_name,username,email,phone,role,is_verified,account_type').maybeSingle();
    setSaving(false);
    if (error) return notify(error.message.includes('duplicate') ? 'اسم المستخدم مستخدم مسبقاً.' : `تعذر حفظ التعديلات: ${error.message}`);
    if (!data) return notify('لم يتم تعديل الحساب: لا توجد صلاحية UPDATE لهذا المستخدم في Supabase.');
    setProfile(data as Profile); setForm({ full_name: data.full_name || '', username: data.username || '', phone: data.phone || '', account_type: data.account_type || 'both' }); setEditing(false); notify('تم حفظ معلومات الحساب بنجاح.');
  };
  const handleLogout = async () => { const result = await logout(); if (result.error) return notify(`تعذر تسجيل الخروج: ${result.error}`); notify('تم تسجيل الخروج.'); navigate('/'); };
  if (!session) return <main dir="rtl" className="mx-auto max-w-xl px-4 py-20 text-center"><UserRound className="mx-auto text-[#e7663c]" size={48}/><h1 className="mt-4 text-2xl font-black text-[#18394c]">تسجيل الدخول مطلوب</h1><p className="mt-2 text-sm font-semibold text-slate-500">سجّل الدخول للوصول إلى حسابك.</p><button onClick={() => navigate('/')} className="mt-6 rounded-xl bg-[#e7663c] px-5 py-3 text-sm font-black text-white">العودة لتسجيل الدخول</button></main>;
  const accountLabel = profile?.role === 'admin' ? 'مدير الموقع' : profile?.role === 'moderator' ? 'مشرف' : profile?.account_type === 'seller' ? 'بائع' : profile?.account_type === 'buyer' ? 'مشتري' : 'مشتري وبائع';
  return <main dir="rtl" className="mx-auto max-w-4xl px-4 py-8 sm:py-12"><div className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm sm:p-8"><div className="flex flex-wrap items-center justify-between gap-4"><div className="flex items-center gap-4"><div className="grid h-16 w-16 place-items-center rounded-2xl bg-[#fff0eb] text-[#e7663c]"><UserRound size={30}/></div><div><p className="text-xs font-black text-[#e7663c]">حساب سوق الوادي</p><h1 className="mt-1 text-2xl font-black text-[#18394c]">{loading ? 'جارٍ التحميل...' : profile?.full_name || 'مستخدم سوق الوادي'}</h1></div></div><button onClick={() => void handleLogout()} className="flex items-center gap-2 rounded-xl border border-rose-100 px-4 py-3 text-xs font-black text-rose-600"><LogOut size={16}/> تسجيل الخروج</button></div>
    {!loading && profile && <div><div className="mt-8 flex items-center justify-between"><h2 className="text-lg font-black text-[#18394c]">معلومات الحساب</h2>{!editing && <button onClick={() => setEditing(true)} className="flex items-center gap-2 rounded-xl bg-[#fff0eb] px-4 py-2.5 text-xs font-black text-[#e7663c]"><Edit3 size={15}/> تعديل المعلومات</button>}</div>
      {editing ? <div className="mt-4 grid gap-4 sm:grid-cols-2"><Field label="الاسم الكامل" value={form.full_name} onChange={v => setForm({ ...form, full_name: v })}/><Field label="اسم المستخدم" value={form.username} onChange={v => setForm({ ...form, username: v })} dir="ltr" placeholder="username"/><Field label="الهاتف" value={form.phone} onChange={v => setForm({ ...form, phone: v })} dir="ltr" placeholder="0673..."/><label className="text-xs font-black text-slate-500">نوع الحساب<select value={form.account_type} onChange={e => setForm({ ...form, account_type: e.target.value as AccountType })} className="mt-2 h-12 w-full rounded-xl border border-slate-200 bg-white px-4 text-sm outline-none focus:border-[#e7663c]"><option value="buyer">مشتري</option><option value="seller">بائع</option><option value="both">مشتري وبائع</option></select></label><div className="flex items-end gap-2 sm:col-span-2"><button disabled={saving} onClick={() => void saveProfile()} className="flex h-12 items-center gap-2 rounded-xl bg-[#e7663c] px-5 text-sm font-black text-white disabled:opacity-60"><Save size={16}/> {saving ? 'جارٍ الحفظ...' : 'حفظ التعديلات'}</button><button disabled={saving} onClick={() => setEditing(false)} className="flex h-12 items-center gap-2 rounded-xl bg-slate-100 px-5 text-sm font-black text-slate-600"><XCircle size={16}/> إلغاء</button></div></div> : <div className="mt-4 grid gap-3 sm:grid-cols-2"><Info label="اسم المستخدم" value={profile.username ? `@${profile.username}` : '—'}/><Info label="البريد الإلكتروني" value={profile.email}/><Info label="الهاتف" value={profile.phone || '—'}/><Info label="نوع الحساب" value={accountLabel}/><Info label="حالة الحساب" value={profile.is_verified ? 'موثّق' : 'نشط'}/></div>}</div>}
    <div className="mt-8 border-t border-slate-100 pt-6"><div className="mb-4 flex items-center justify-between"><h2 className="text-lg font-black text-[#18394c]">إعلاناتي</h2><span className="rounded-full bg-slate-100 px-3 py-1 text-xs font-black text-slate-500">{listings.length} إعلان</span></div>{listings.length === 0 ? <div className="rounded-2xl bg-slate-50 p-6 text-center text-sm font-bold text-slate-400">لم تنشر أي إعلان بعد.</div> : <div className="grid gap-3">{listings.map(item => { const state = listingStatus[item.status]; const StatusIcon = state.icon; return <div key={item.id} className="flex items-center gap-3 rounded-2xl border border-slate-100 p-3"><img src={item.image_urls?.[0] || '/hero-eloued.webp'} className="h-16 w-16 rounded-xl object-cover" alt=""/><div className="min-w-0 flex-1"><h3 className="truncate text-sm font-black text-[#18394c]">{item.title}</h3><p className="mt-1 text-xs font-bold text-slate-400">{item.municipalities?.name || '—'} · {item.categories?.name || '—'} · {Number(item.price).toLocaleString('fr-DZ')} دج</p></div><span className={`flex shrink-0 items-center gap-1 rounded-full px-2.5 py-1.5 text-[10px] font-black ${state.className}`}><StatusIcon size={13}/>{state.label}</span></div>; })}</div>}</div><div className="mt-6 flex flex-wrap gap-3"><button onClick={() => navigate('/')} className="rounded-xl bg-[#e7663c] px-5 py-3 text-sm font-black text-white">تصفح الإعلانات</button>{profile && ['admin', 'moderator'].includes(profile.role) && <button onClick={() => navigate('/admin')} className="flex items-center gap-2 rounded-xl bg-[#18394c] px-5 py-3 text-sm font-black text-white"><ShieldCheck size={17}/> لوحة الإدارة</button>}</div></div></main>;
}
function Field({ label, value, onChange, dir, placeholder }: { label: string; value: string; onChange: (value: string) => void; dir?: 'ltr' | 'rtl'; placeholder?: string }) { return <label className="text-xs font-black text-slate-500">{label}<input dir={dir} placeholder={placeholder} value={value} onChange={e => onChange(e.target.value)} className="mt-2 h-12 w-full rounded-xl border border-slate-200 px-4 text-sm outline-none focus:border-[#e7663c]"/></label>; }
function Info({ label, value }: { label: string; value: string }) { return <div className="rounded-2xl bg-slate-50 p-4"><span className="block text-[11px] font-bold text-slate-400">{label}</span><b className="mt-1 block break-all text-sm text-[#18394c]">{value}</b></div>; }
