import { useEffect, useState } from 'react';
import { LogOut, ShieldCheck, UserRound } from 'lucide-react';
import { useNavigate } from 'react-router-dom';
import { useApp } from '../context/AppContext';
import { supabase } from '../lib/supabase';

type Profile = { full_name: string; username: string; email: string; role: 'user' | 'moderator' | 'admin'; is_verified: boolean };
export function AccountPage() {
  const { session, notify } = useApp(); const navigate = useNavigate(); const [profile, setProfile] = useState<Profile | null>(null); const [loading, setLoading] = useState(true);
  useEffect(() => { let active = true; const load = async () => { if (!supabase || !session) { setLoading(false); return; } const { data } = await supabase.from('profiles').select('full_name,username,email,role,is_verified').eq('id', session.user.id).limit(1).maybeSingle(); if (active) { setProfile(data as Profile | null); setLoading(false); } }; void load(); return () => { active = false; }; }, [session]);
  const logout = async () => { if (supabase) await supabase.auth.signOut(); notify('تم تسجيل الخروج.'); navigate('/'); };
  if (!session) return <main dir="rtl" className="mx-auto max-w-xl px-4 py-20 text-center"><UserRound className="mx-auto text-[#e7663c]" size={48}/><h1 className="mt-4 text-2xl font-black text-[#18394c]">تسجيل الدخول مطلوب</h1><p className="mt-2 text-sm font-semibold text-slate-500">سجّل الدخول للوصول إلى حسابك.</p><button onClick={() => navigate('/')} className="mt-6 rounded-xl bg-[#e7663c] px-5 py-3 text-sm font-black text-white">العودة لتسجيل الدخول</button></main>;
  return <main dir="rtl" className="mx-auto max-w-3xl px-4 py-8 sm:py-12"><div className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm sm:p-8"><div className="flex flex-wrap items-center justify-between gap-4"><div className="flex items-center gap-4"><div className="grid h-16 w-16 place-items-center rounded-2xl bg-[#fff0eb] text-[#e7663c]"><UserRound size={30}/></div><div><p className="text-xs font-black text-[#e7663c]">حساب سوق الوادي</p><h1 className="mt-1 text-2xl font-black text-[#18394c]">{loading ? 'جارٍ التحميل...' : profile?.full_name || 'مستخدم سوق الوادي'}</h1></div></div><button onClick={() => void logout()} className="flex items-center gap-2 rounded-xl border border-rose-100 px-4 py-3 text-xs font-black text-rose-600"><LogOut size={16}/> تسجيل الخروج</button></div>{!loading && profile && <div className="mt-8 grid gap-3 sm:grid-cols-2"><Info label="اسم المستخدم" value={`@${profile.username}`}/><Info label="البريد الإلكتروني" value={profile.email}/><Info label="نوع الحساب" value={profile.role === 'admin' ? 'مدير الموقع' : profile.role === 'moderator' ? 'مشرف' : 'مستخدم'}/><Info label="حالة الحساب" value={profile.is_verified ? 'موثّق' : 'نشط'}/></div>}<div className="mt-6 flex flex-wrap gap-3"><button onClick={() => navigate('/')} className="rounded-xl bg-[#e7663c] px-5 py-3 text-sm font-black text-white">تصفح الإعلانات</button>{profile && ['admin','moderator'].includes(profile.role) && <button onClick={() => navigate('/admin')} className="flex items-center gap-2 rounded-xl bg-[#18394c] px-5 py-3 text-sm font-black text-white"><ShieldCheck size={17}/> لوحة الإدارة</button>}</div></div></main>;
}
function Info({ label, value }: { label: string; value: string }) { return <div className="rounded-2xl bg-slate-50 p-4"><span className="block text-[11px] font-bold text-slate-400">{label}</span><b className="mt-1 block break-all text-sm text-[#18394c]">{value}</b></div>; }
