import { useEffect, useMemo, useState } from 'react';
import { Ban, CheckCircle2, Clock3, Edit3, LayoutDashboard, LogIn, RefreshCw, ShieldCheck, Trash2, UserCheck, UserCog, XCircle } from 'lucide-react';
import { useNavigate } from 'react-router-dom';
import type { ReactNode } from 'react';
import { useApp } from '../context/AppContext';
import { supabase } from '../lib/supabase';
import { formatPrice } from '../lib/format';

type AdminListing = { id: string; title: string; price: number; description?: string; status: 'draft' | 'active' | 'sold' | 'archived'; image_urls?: string[]; created_at: string; seller_id: string; profiles?: { full_name: string; is_banned: boolean } | null; municipalities?: { name: string } | null; categories?: { name: string } | null };
type AdminProfile = { id: string; full_name: string; username?: string; email?: string; role: 'user' | 'moderator' | 'admin'; is_banned: boolean; created_at: string };
type Tab = 'overview' | 'pending' | 'listings' | 'users';
const statusLabel: Record<string, string> = { draft: 'قيد المراجعة', active: 'منشور', sold: 'مباع', archived: 'مؤرشف' };

export function AdminPage() {
  const { session, notify } = useApp(); const navigate = useNavigate();
  const [tab, setTab] = useState<Tab>('overview'); const [listings, setListings] = useState<AdminListing[]>([]); const [profiles, setProfiles] = useState<AdminProfile[]>([]); const [role, setRole] = useState(''); const [loading, setLoading] = useState(true); const [busy, setBusy] = useState('');
  const load = async () => {
    if (!supabase || !session) { setLoading(false); return; } setLoading(true);
    const me = await supabase.from('profiles').select('id,full_name,username,email,role,is_banned,created_at').eq('id', session.user.id).limit(1).maybeSingle();
    setRole(me.data?.role || ''); if (!me.data || me.data.is_banned || !['admin', 'moderator'].includes(me.data.role)) { setLoading(false); return; }
    const [lr, ur] = await Promise.all([
      supabase.from('listings').select('id,title,price,description,status,image_urls,created_at,seller_id,profiles(full_name,is_banned),municipalities(name),categories(name)').order('created_at', { ascending: false }).limit(200),
      supabase.from('profiles').select('id,full_name,username,email,role,is_banned,created_at').order('created_at', { ascending: false }).limit(200),
    ]);
    if (lr.error) notify(`خطأ الإعلانات: ${lr.error.message}`); if (ur.error) notify(`خطأ المستخدمين: ${ur.error.message}`);
    setListings((lr.data || []).map((x: any) => ({ ...x, profiles: Array.isArray(x.profiles) ? x.profiles[0] || null : x.profiles, municipalities: Array.isArray(x.municipalities) ? x.municipalities[0] || null : x.municipalities, categories: Array.isArray(x.categories) ? x.categories[0] || null : x.categories })) as AdminListing[]);
    setProfiles((ur.data || []) as AdminProfile[]); setLoading(false);
  };
  useEffect(() => { void load(); }, [session]);
  const pending = useMemo(() => listings.filter(x => x.status === 'draft'), [listings]);
  const canManageUsers = role === 'admin';
  const updateListing = async (id: string, patch: Record<string, unknown>, message: string) => { if (!supabase) return; setBusy(id); const { error } = await supabase.from('listings').update({ ...patch, updated_at: new Date().toISOString() }).eq('id', id); setBusy(''); if (error) notify(error.message); else { notify(message); void load(); } };
  const editListing = async (item: AdminListing) => { const title = window.prompt('عنوان الإعلان:', item.title); if (title === null) return; const priceText = window.prompt('السعر بالدج:', String(item.price)); if (priceText === null) return; const description = window.prompt('الوصف:', item.description || ''); if (description === null) return; const price = Number(priceText); if (!title.trim() || !Number.isFinite(price) || price < 0) return notify('العنوان والسعر غير صحيحين.'); await updateListing(item.id, { title: title.trim(), price, description }, 'تم تعديل الإعلان.'); };
  const deleteListing = async (id: string) => { if (!supabase || !window.confirm('حذف الإعلان نهائياً؟')) return; setBusy(id); const { error } = await supabase.from('listings').delete().eq('id', id); setBusy(''); if (error) notify(error.message); else { notify('تم حذف الإعلان نهائياً.'); void load(); } };
  const toggleBan = async (user: AdminProfile) => { if (!supabase || !canManageUsers || user.id === session?.user.id) return notify('لا يمكنك حظر حسابك أو لا تملك صلاحية إدارة المستخدمين.'); if (!window.confirm(user.is_banned ? 'إلغاء حظر المستخدم؟' : 'حظر المستخدم؟')) return; setBusy(user.id); const { error } = await supabase.from('profiles').update({ is_banned: !user.is_banned }).eq('id', user.id); setBusy(''); if (error) notify(error.message); else { notify(user.is_banned ? 'تم إلغاء الحظر.' : 'تم حظر المستخدم.'); void load(); } };
  const changeRole = async (user: AdminProfile) => { if (!supabase || !canManageUsers || user.id === session?.user.id) return notify('لا يمكنك تغيير دور حسابك الحالي.'); const next = window.prompt('اكتب الدور: user أو moderator أو admin', user.role); if (!next || !['user', 'moderator', 'admin'].includes(next)) return notify('الدور غير صحيح.'); setBusy(user.id); const { error } = await supabase.from('profiles').update({ role: next }).eq('id', user.id); setBusy(''); if (error) notify(error.message); else { notify('تم تحديث دور المستخدم.'); void load(); } };

  if (!session) return <Access title="تسجيل الدخول مطلوب" text="سجل الدخول بحساب إداري أو مشرف للوصول إلى لوحة التحكم." onBack={() => navigate('/')} icon={<LogIn/>}/>;
  if (loading) return <main className="mx-auto max-w-xl px-4 py-20 text-center text-sm font-bold text-slate-500"><RefreshCw className="mx-auto mb-3 animate-spin"/>جارٍ تحميل بيانات لوحة التحكم...</main>;
  if (!['admin', 'moderator'].includes(role)) return <Access title="ليس لديك صلاحية الوصول" text="عيّن دور حسابك إلى admin أو moderator من Supabase ثم سجّل الخروج والدخول." onBack={() => navigate('/')} icon={<ShieldCheck/>}/>;
  const displayed = tab === 'pending' ? pending : listings;
  const stats = [{ label: 'الإعلانات', value: listings.length, icon: LayoutDashboard }, { label: 'قيد المراجعة', value: pending.length, icon: Clock3 }, { label: 'منشور', value: listings.filter(x => x.status === 'active').length, icon: CheckCircle2 }, { label: 'محظورون', value: profiles.filter(x => x.is_banned).length, icon: Ban }];
  return <main dir="rtl" className="mx-auto max-w-[1400px] px-3 py-6 sm:px-6 sm:py-10"><div className="mb-7 flex flex-wrap items-center justify-between gap-4"><div><div className="flex items-center gap-2 text-xs font-black text-[#e7663c]"><ShieldCheck size={16}/> مركز إدارة سوق الوادي · {role === 'moderator' ? 'moderator' : role}</div><h1 className="mt-2 text-2xl font-black text-[#18394c] sm:text-3xl">لوحة التحكم</h1><p className="mt-1 text-sm font-semibold text-slate-400">إدارة الإعلانات والمستخدمين والمشرفين.</p></div><button onClick={() => void load()} className="flex items-center gap-2 rounded-xl border border-slate-200 bg-white px-4 py-3 text-xs font-black text-slate-600"><RefreshCw size={15}/> تحديث</button></div>
    <div className="mb-6 grid grid-cols-2 gap-3 lg:grid-cols-4">{stats.map(s => <div key={s.label} className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"><s.icon className="mb-4 text-[#e7663c]" size={21}/><b className="block text-2xl font-black text-[#18394c]">{s.value}</b><span className="mt-1 block text-xs font-bold text-slate-400">{s.label}</span></div>)}</div>
    <div className="mb-5 flex gap-2 overflow-x-auto rounded-2xl border border-slate-200 bg-white p-2">{([{ id: 'overview', label: 'نظرة عامة' }, { id: 'pending', label: `المراجعة (${pending.length})` }, { id: 'listings', label: 'كل الإعلانات' }, { id: 'users', label: 'المستخدمون والمشرفون' }] as { id: Tab; label: string }[]).map(x => <button key={x.id} onClick={() => setTab(x.id)} className={`whitespace-nowrap rounded-xl px-4 py-2.5 text-xs font-black ${tab === x.id ? 'bg-[#18394c] text-white' : 'text-slate-500 hover:bg-slate-50'}`}>{x.label}</button>)}</div>
    {tab === 'overview' && <div className="grid gap-5 lg:grid-cols-2"><section className="rounded-2xl border border-slate-200 bg-white p-5"><h2 className="mb-4 font-black">آخر الإعلانات قيد المراجعة</h2><ListingTable items={pending.slice(0, 8)} busy={busy} role={role} onApprove={id => void updateListing(id, { status: 'active' }, 'تم قبول الإعلان.')} onReject={id => void updateListing(id, { status: 'archived' }, 'تم رفض الإعلان.')} onDelete={deleteListing} onEdit={editListing}/></section><section className="rounded-2xl border border-slate-200 bg-white p-5"><h2 className="mb-4 font-black">حالة المنصة</h2><p className="rounded-xl bg-emerald-50 p-4 text-sm font-bold leading-7 text-emerald-800">يمكنك الآن قبول الإعلانات، تعديلها، حذفها، حظر المستخدمين وإضافة مشرفين من تبويب المستخدمين.</p><p className="mt-3 rounded-xl bg-slate-50 p-4 text-xs font-bold leading-6 text-slate-500">عدد الإعلانات الحالي في قاعدة البيانات: {listings.length}. إذا كانت صفر، فهذا يعني أنه لم يتم إرسال أي إعلان بعد.</p></section></div>}
    {(tab === 'pending' || tab === 'listings') && <section className="rounded-2xl border border-slate-200 bg-white p-4 sm:p-6"><div className="mb-5 flex items-center justify-between"><h2 className="font-black">{tab === 'pending' ? 'الإعلانات قيد المراجعة' : 'كل الإعلانات'}</h2><span className="rounded-full bg-slate-100 px-3 py-1.5 text-[11px] font-black text-slate-500">{displayed.length} إعلان</span></div><ListingTable items={displayed} busy={busy} role={role} onApprove={id => void updateListing(id, { status: 'active' }, 'تم قبول الإعلان.')} onReject={id => void updateListing(id, { status: 'archived' }, 'تمت أرشفة الإعلان.')} onDelete={deleteListing} onEdit={editListing}/></section>}
    {tab === 'users' && <section className="rounded-2xl border border-slate-200 bg-white p-4 sm:p-6"><div className="mb-5 flex items-center justify-between"><h2 className="font-black">المستخدمون والمشرفون</h2><span className="rounded-full bg-slate-100 px-3 py-1.5 text-[11px] font-black text-slate-500">{profiles.length} مستخدم</span></div><div className="overflow-x-auto"><table className="w-full min-w-[720px] text-right text-xs"><thead><tr className="border-b border-slate-100 text-slate-400"><th className="p-3">الاسم واسم المستخدم</th><th className="p-3">الدور</th><th className="p-3">الحالة</th><th className="p-3">الإجراءات</th></tr></thead><tbody>{profiles.map(u => <tr key={u.id} className="border-b border-slate-50"><td className="p-3"><b className="block">{u.full_name || 'بدون اسم'}</b><small className="text-slate-400">@{u.username || '—'} · {u.email || '—'}</small></td><td className="p-3 font-black text-[#18394c]">{u.role}</td><td className="p-3"><span className={u.is_banned ? 'font-black text-rose-600' : 'font-black text-emerald-600'}>{u.is_banned ? 'محظور' : 'نشط'}</span></td><td className="p-3"><div className="flex gap-2"><button disabled={!canManageUsers || busy === u.id} onClick={() => void changeRole(u)} className="flex items-center gap-1 rounded-lg bg-blue-50 px-3 py-2 text-[11px] font-black text-blue-700"><UserCog size={14}/> تغيير الدور</button><button disabled={!canManageUsers || busy === u.id} onClick={() => void toggleBan(u)} className={`flex items-center gap-1 rounded-lg px-3 py-2 text-[11px] font-black ${u.is_banned ? 'bg-emerald-50 text-emerald-700' : 'bg-rose-50 text-rose-700'}`}>{u.is_banned ? <UserCheck size={14}/> : <Ban size={14}/>} {u.is_banned ? 'إلغاء الحظر' : 'حظر'}</button></div></td></tr>)}</tbody></table></div></section>}
  </main>;
}
function Access({ title, text, onBack, icon }: { title: string; text: string; onBack: () => void; icon: ReactNode }) { return <main className="mx-auto max-w-xl px-4 py-20 text-center">{icon}<h1 className="mt-4 text-2xl font-black">{title}</h1><p className="mt-2 text-sm text-slate-500">{text}</p><button onClick={onBack} className="mt-6 rounded-xl bg-[#18394c] px-5 py-3 text-sm font-black text-white">العودة للموقع</button></main>; }
function ListingTable({ items, busy, role, onApprove, onReject, onDelete, onEdit }: { items: AdminListing[]; busy: string; role: string; onApprove: (id: string) => void; onReject: (id: string) => void; onDelete: (id: string) => void; onEdit: (item: AdminListing) => void }) { if (!items.length) return <div className="rounded-xl bg-slate-50 p-8 text-center text-sm font-bold text-slate-400">لا توجد إعلانات حالياً في قاعدة البيانات.</div>; return <div className="overflow-x-auto"><table className="w-full min-w-[800px] text-right text-xs"><thead><tr className="border-b border-slate-100 text-slate-400"><th className="p-3">الإعلان</th><th className="p-3">البائع</th><th className="p-3">السعر</th><th className="p-3">الحالة</th><th className="p-3">الإجراءات</th></tr></thead><tbody>{items.map(i => <tr key={i.id} className="border-b border-slate-50"><td className="p-3"><div className="flex items-center gap-3"><img src={i.image_urls?.[0] || '/hero-eloued.webp'} className="h-12 w-12 rounded-lg object-cover" alt=""/><div><b className="block max-w-[240px] truncate">{i.title}</b><small className="text-slate-400">{i.municipalities?.name || '—'} · {i.categories?.name || '—'}</small></div></div></td><td className="p-3 font-bold">{i.profiles?.full_name || 'مستخدم'}</td><td className="p-3 font-black text-[#e7663c]">{formatPrice(i.price)} دج</td><td className="p-3"><span className="rounded-full bg-slate-100 px-2 py-1 text-[10px] font-black">{statusLabel[i.status]}</span></td><td className="p-3"><div className="flex gap-1.5">{i.status !== 'active' && <button disabled={busy === i.id} onClick={() => onApprove(i.id)} title="قبول" className="grid h-8 w-8 place-items-center rounded-lg bg-emerald-50 text-emerald-700"><CheckCircle2 size={15}/></button>}{i.status !== 'archived' && <button disabled={busy === i.id} onClick={() => onReject(i.id)} title="أرشفة" className="grid h-8 w-8 place-items-center rounded-lg bg-amber-50 text-amber-700"><XCircle size={15}/></button>}<button disabled={busy === i.id} onClick={() => onEdit(i)} title="تعديل" className="grid h-8 w-8 place-items-center rounded-lg bg-blue-50 text-blue-700"><Edit3 size={15}/></button><button disabled={busy === i.id || role === 'moderator'} onClick={() => onDelete(i.id)} title="حذف نهائي (للمدير)" className="grid h-8 w-8 place-items-center rounded-lg bg-rose-50 text-rose-700"><Trash2 size={15}/></button></div></td></tr>)}</tbody></table></div>; }
