import { useEffect, useMemo, useState } from 'react';
import { Ban, CheckCircle2, Clock3, LayoutDashboard, LogIn, RefreshCw, ShieldCheck, Trash2, UserCheck, Users, XCircle } from 'lucide-react';
import { useNavigate } from 'react-router-dom';
import { useApp } from '../context/AppContext';
import { supabase } from '../lib/supabase';
import { formatPrice } from '../lib/format';

type AdminListing = { id: string; title: string; price: number; status: 'draft' | 'active' | 'sold' | 'archived'; image_urls?: string[]; created_at: string; seller_id: string; profiles?: { full_name: string; is_banned: boolean } | null; municipalities?: { name: string } | null; categories?: { name: string } | null };
type AdminProfile = { id: string; full_name: string; phone: string | null; role: 'user' | 'moderator' | 'admin'; is_banned: boolean; created_at: string };
type Tab = 'overview' | 'pending' | 'listings' | 'users';

const statusLabel: Record<string, string> = { draft: 'قيد المراجعة', active: 'منشور', sold: 'مباع', archived: 'مؤرشف' };

export function AdminPage() {
  const { session, notify } = useApp();
  const navigate = useNavigate();
  const [tab, setTab] = useState<Tab>('overview');
  const [listings, setListings] = useState<AdminListing[]>([]);
  const [profiles, setProfiles] = useState<AdminProfile[]>([]);
  const [admin, setAdmin] = useState(false);
  const [loading, setLoading] = useState(true);
  const [busy, setBusy] = useState('');

  const load = async () => {
    if (!supabase || !session) { setLoading(false); return; }
    setLoading(true);
    const profileResult = await supabase.from('profiles').select('id,full_name,phone,role,is_banned,created_at').eq('id', session.user.id).limit(1).maybeSingle();
    const allowed = profileResult.data?.role === 'admin' && !profileResult.data.is_banned;
    setAdmin(Boolean(allowed));
    if (!allowed) { setLoading(false); return; }
    const [listingResult, usersResult] = await Promise.all([
      supabase.from('listings').select('id,title,price,status,image_urls,created_at,seller_id,profiles(full_name,is_banned),municipalities(name),categories(name)').order('created_at', { ascending: false }).limit(200),
      supabase.from('profiles').select('id,full_name,phone,role,is_banned,created_at').order('created_at', { ascending: false }).limit(200),
    ]);
    if (listingResult.error || usersResult.error) notify('تعذر تحميل بيانات لوحة التحكم.');
    const normalizedListings = (listingResult.data || []).map((item: any) => ({ ...item, profiles: Array.isArray(item.profiles) ? item.profiles[0] || null : item.profiles, municipalities: Array.isArray(item.municipalities) ? item.municipalities[0] || null : item.municipalities, categories: Array.isArray(item.categories) ? item.categories[0] || null : item.categories })) as AdminListing[];
    setListings(normalizedListings); setProfiles((usersResult.data || []) as AdminProfile[]); setLoading(false);
  };

  useEffect(() => { void load(); }, [session]);
  const pending = useMemo(() => listings.filter(item => item.status === 'draft'), [listings]);
  const stats = [{ label: 'إجمالي الإعلانات', value: listings.length, icon: LayoutDashboard, color: 'text-[#e7663c] bg-[#fff0eb]' }, { label: 'قيد المراجعة', value: pending.length, icon: Clock3, color: 'text-amber-700 bg-amber-50' }, { label: 'إعلانات منشورة', value: listings.filter(x => x.status === 'active').length, icon: CheckCircle2, color: 'text-emerald-700 bg-emerald-50' }, { label: 'مستخدمون محظورون', value: profiles.filter(x => x.is_banned).length, icon: Ban, color: 'text-rose-700 bg-rose-50' }];

  const updateListing = async (id: string, status: 'active' | 'archived') => { if (!supabase) return; setBusy(id); const { error } = await supabase.from('listings').update({ status, updated_at: new Date().toISOString() }).eq('id', id); setBusy(''); if (error) notify(error.message); else { notify(status === 'active' ? 'تم قبول الإعلان ونشره.' : 'تم رفض الإعلان وأرشفته.'); void load(); } };
  const deleteListing = async (id: string) => { if (!supabase || !window.confirm('هل تريد حذف هذا الإعلان نهائياً؟')) return; setBusy(id); const { error } = await supabase.from('listings').delete().eq('id', id); setBusy(''); if (error) notify(error.message); else { notify('تم حذف الإعلان.'); void load(); } };
  const toggleBan = async (profile: AdminProfile) => { if (!supabase || profile.id === session?.user.id) return notify('لا يمكنك حظر حسابك الإداري.'); const action = profile.is_banned ? 'إلغاء حظر' : 'حظر'; if (!window.confirm(`هل تريد ${action} هذا المستخدم؟`)) return; setBusy(profile.id); const { error } = await supabase.from('profiles').update({ is_banned: !profile.is_banned }).eq('id', profile.id); setBusy(''); if (error) notify(error.message); else { notify(profile.is_banned ? 'تم إلغاء حظر المستخدم.' : 'تم حظر المستخدم.'); void load(); } };

  if (!session) return <main className="mx-auto max-w-xl px-4 py-20 text-center"><LogIn className="mx-auto text-[#e7663c]" size={42}/><h1 className="mt-4 text-2xl font-black">تسجيل الدخول مطلوب</h1><p className="mt-2 text-sm text-slate-500">سجل الدخول بحساب إداري للوصول إلى لوحة التحكم.</p><button onClick={() => navigate('/')} className="mt-6 rounded-xl bg-[#e7663c] px-5 py-3 text-sm font-black text-white">العودة للموقع</button></main>;
  if (loading) return <main className="mx-auto max-w-[1360px] px-4 py-20 text-center text-sm font-bold text-slate-500"><RefreshCw className="mx-auto animate-spin"/> جارٍ التحقق من صلاحيات الإدارة...</main>;
  if (!admin) return <main className="mx-auto max-w-xl px-4 py-20 text-center"><ShieldCheck className="mx-auto text-rose-500" size={42}/><h1 className="mt-4 text-2xl font-black">ليس لديك صلاحية الوصول</h1><p className="mt-2 text-sm text-slate-500">هذه الصفحة مخصصة لمديري سوق الوادي فقط.</p><button onClick={() => navigate('/')} className="mt-6 rounded-xl bg-[#18394c] px-5 py-3 text-sm font-black text-white">العودة للموقع</button></main>;

  const displayedListings = tab === 'pending' ? pending : listings;
  return <main dir="rtl" className="mx-auto max-w-[1400px] px-3 py-6 sm:px-6 sm:py-10"><div className="mb-7 flex flex-wrap items-center justify-between gap-4"><div><div className="flex items-center gap-2 text-xs font-black text-[#e7663c]"><ShieldCheck size={16}/> مركز إدارة سوق الوادي</div><h1 className="mt-2 text-2xl font-black text-[#18394c] sm:text-3xl">لوحة التحكم</h1><p className="mt-1 text-sm font-semibold text-slate-400">إدارة الإعلانات والمستخدمين والمحتوى بأمان.</p></div><button onClick={() => void load()} className="flex items-center gap-2 rounded-xl border border-slate-200 bg-white px-4 py-3 text-xs font-black text-slate-600"><RefreshCw size={15}/> تحديث البيانات</button></div>
    <div className="mb-6 grid grid-cols-2 gap-3 lg:grid-cols-4">{stats.map(item => <div key={item.label} className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"><div className={`mb-4 grid h-10 w-10 place-items-center rounded-xl ${item.color}`}><item.icon size={19}/></div><b className="block text-2xl font-black text-[#18394c]">{item.value}</b><span className="mt-1 block text-xs font-bold text-slate-400">{item.label}</span></div>)}</div>
    <div className="mb-5 flex gap-2 overflow-x-auto rounded-2xl border border-slate-200 bg-white p-2">{([{ id: 'overview', label: 'نظرة عامة' }, { id: 'pending', label: `المراجعة (${pending.length})` }, { id: 'listings', label: 'كل الإعلانات' }, { id: 'users', label: 'المستخدمون' }] as { id: Tab; label: string }[]).map(item => <button key={item.id} onClick={() => setTab(item.id)} className={`whitespace-nowrap rounded-xl px-4 py-2.5 text-xs font-black ${tab === item.id ? 'bg-[#18394c] text-white' : 'text-slate-500 hover:bg-slate-50'}`}>{item.label}</button>)}</div>
    {tab === 'overview' && <div className="grid gap-5 lg:grid-cols-[1.35fr_1fr]"><section className="rounded-2xl border border-slate-200 bg-white p-5"><div className="mb-4 flex items-center justify-between"><h2 className="font-black">آخر الإعلانات المرسلة</h2><button onClick={() => setTab('pending')} className="text-xs font-black text-[#e7663c]">عرض المراجعة</button></div><ListingTable items={pending.slice(0, 5)} busy={busy} onApprove={id => void updateListing(id, 'active')} onReject={id => void updateListing(id, 'archived')} onDelete={id => void deleteListing(id)} /></section><section className="rounded-2xl border border-slate-200 bg-white p-5"><h2 className="mb-4 font-black">حالة المستخدمين</h2><div className="grid gap-3">{profiles.slice(0, 6).map(user => <div key={user.id} className="flex items-center justify-between rounded-xl bg-slate-50 p-3"><span className="flex items-center gap-2 text-xs font-bold"><span className="grid h-8 w-8 place-items-center rounded-full bg-[#e6f2f0] text-[#287f72]">{user.full_name?.slice(0, 1) || 'م'}</span>{user.full_name || 'مستخدم جديد'}</span><span className={`text-[10px] font-black ${user.is_banned ? 'text-rose-600' : 'text-emerald-600'}`}>{user.is_banned ? 'محظور' : 'نشط'}</span></div>)}</div></section></div>}
    {(tab === 'pending' || tab === 'listings') && <section className="rounded-2xl border border-slate-200 bg-white p-4 sm:p-6"><div className="mb-5 flex items-center justify-between"><h2 className="font-black">{tab === 'pending' ? 'الإعلانات قيد المراجعة' : 'كل الإعلانات'}</h2><span className="rounded-full bg-slate-100 px-3 py-1.5 text-[11px] font-black text-slate-500">{displayedListings.length} إعلان</span></div><ListingTable items={displayedListings} busy={busy} onApprove={id => void updateListing(id, 'active')} onReject={id => void updateListing(id, 'archived')} onDelete={id => void deleteListing(id)} /></section>}
    {tab === 'users' && <section className="rounded-2xl border border-slate-200 bg-white p-4 sm:p-6"><div className="mb-5 flex items-center justify-between"><h2 className="font-black">إدارة المستخدمين</h2><span className="rounded-full bg-slate-100 px-3 py-1.5 text-[11px] font-black text-slate-500">{profiles.length} مستخدم</span></div><div className="overflow-x-auto"><table className="w-full min-w-[650px] text-right text-xs"><thead><tr className="border-b border-slate-100 text-slate-400"><th className="p-3">المستخدم</th><th className="p-3">الهاتف</th><th className="p-3">الدور</th><th className="p-3">الحالة</th><th className="p-3">الإجراء</th></tr></thead><tbody>{profiles.map(user => <tr key={user.id} className="border-b border-slate-50"><td className="p-3 font-black">{user.full_name || 'بدون اسم'}</td><td className="p-3 text-slate-500">{user.phone || '—'}</td><td className="p-3 text-slate-500">{user.role}</td><td className="p-3"><span className={user.is_banned ? 'font-black text-rose-600' : 'font-black text-emerald-600'}>{user.is_banned ? 'محظور' : 'نشط'}</span></td><td className="p-3"><button disabled={busy === user.id} onClick={() => void toggleBan(user)} className={`flex items-center gap-1 rounded-lg px-3 py-2 text-[11px] font-black ${user.is_banned ? 'bg-emerald-50 text-emerald-700' : 'bg-rose-50 text-rose-700'}`}>{user.is_banned ? <UserCheck size={14}/> : <Ban size={14}/>} {user.is_banned ? 'إلغاء الحظر' : 'حظر المستخدم'}</button></td></tr>)}</tbody></table></div></section>}
  </main>;
}

function ListingTable({ items, busy, onApprove, onReject, onDelete }: { items: AdminListing[]; busy: string; onApprove: (id: string) => void; onReject: (id: string) => void; onDelete: (id: string) => void }) {
  if (!items.length) return <div className="rounded-xl bg-slate-50 p-8 text-center text-sm font-bold text-slate-400">لا توجد إعلانات في هذه القائمة.</div>;
  return <div className="overflow-x-auto"><table className="w-full min-w-[760px] text-right text-xs"><thead><tr className="border-b border-slate-100 text-slate-400"><th className="p-3">الإعلان</th><th className="p-3">البائع</th><th className="p-3">السعر</th><th className="p-3">الحالة</th><th className="p-3">الإجراءات</th></tr></thead><tbody>{items.map(item => <tr key={item.id} className="border-b border-slate-50"><td className="p-3"><div className="flex items-center gap-3"><img src={item.image_urls?.[0] || '/hero-eloued.webp'} className="h-12 w-12 rounded-lg object-cover" alt=""/><div><b className="block max-w-[250px] truncate">{item.title}</b><small className="text-slate-400">{item.municipalities?.name || '—'} · {item.categories?.name || '—'}</small></div></div></td><td className="p-3 font-bold text-slate-600">{item.profiles?.full_name || 'مستخدم'}</td><td className="p-3 font-black text-[#e7663c]">{formatPrice(item.price)} دج</td><td className="p-3"><span className="rounded-full bg-slate-100 px-2 py-1 text-[10px] font-black text-slate-600">{statusLabel[item.status]}</span></td><td className="p-3"><div className="flex gap-1.5">{item.status !== 'active' && <button disabled={busy === item.id} onClick={() => onApprove(item.id)} title="قبول ونشر" className="grid h-8 w-8 place-items-center rounded-lg bg-emerald-50 text-emerald-700"><CheckCircle2 size={15}/></button>}{item.status !== 'archived' && <button disabled={busy === item.id} onClick={() => onReject(item.id)} title="رفض وأرشفة" className="grid h-8 w-8 place-items-center rounded-lg bg-amber-50 text-amber-700"><XCircle size={15}/></button>}<button disabled={busy === item.id} onClick={() => onDelete(item.id)} title="حذف نهائي" className="grid h-8 w-8 place-items-center rounded-lg bg-rose-50 text-rose-700"><Trash2 size={15}/></button></div></td></tr>)}</tbody></table></div>;
}
