import { useEffect, useMemo, useState } from 'react';
import { Archive, BarChart3, CheckCircle2, Clock3, Edit3, Eye, LogIn, Plus, RefreshCw, ShoppingBag, Sparkles, XCircle } from 'lucide-react';
import { useNavigate } from 'react-router-dom';
import { useApp } from '../context/AppContext';
import { supabase } from '../lib/supabase';
import { formatPrice } from '../lib/format';

type MyListing = { id:string; title:string; price:number; image_urls?:string[]; status:'draft'|'active'|'sold'|'archived'; rejection_reason?:string|null; created_at:string; published_at?:string|null; views_count?:number; republish_available_at?:string|null };
const labels = { draft:'قيد المراجعة', active:'منشور', sold:'مباع', archived:'مؤرشف' } as const;
const tone = { draft:'bg-amber-50 text-amber-700', active:'bg-emerald-50 text-emerald-700', sold:'bg-blue-50 text-blue-700', archived:'bg-slate-100 text-slate-600' } as const;

export function MyListingsPage() {
  const { session, notify, setModal } = useApp(); const navigate = useNavigate();
  const [items,setItems]=useState<MyListing[]>([]); const [loading,setLoading]=useState(true); const [busy,setBusy]=useState('');
  const load=async()=>{ if(!supabase||!session){setLoading(false);return;} setLoading(true); const {data,error}=await supabase.from('listings').select('id,title,price,image_urls,status,rejection_reason,created_at,published_at,views_count,republish_available_at').eq('seller_id',session.user.id).order('created_at',{ascending:false}); if(error) notify(error.message); else setItems((data||[]) as MyListing[]); setLoading(false); };
  useEffect(()=>{void load();},[session]);
  const counts=useMemo(()=>({all:items.length,pending:items.filter(x=>x.status==='draft').length,active:items.filter(x=>x.status==='active').length,sold:items.filter(x=>x.status==='sold').length}),[items]);
  const canRepublish=(item:MyListing)=>item.status==='active' && new Date(item.republish_available_at || (item.published_at ? new Date(new Date(item.published_at).getTime()+7*86400000).toISOString() : 0)).getTime()<=Date.now();
  const changeStatus=async(id:string,status:'sold'|'archived')=>{ if(!supabase||!window.confirm(status==='sold'?'تأكيد أن الإعلان مباع؟':'أرشفة الإعلان؟'))return; setBusy(id); const {error}=await supabase.from('listings').update({status}).eq('id',id); setBusy(''); if(error) notify(error.message); else {notify(status==='sold'?'تم وضع الإعلان كمباع.':'تمت أرشفة الإعلان.');void load();} };
  const republish=async(id:string)=>{ if(!supabase)return; setBusy(id); const {error}=await supabase.rpc('republish_listing',{p_listing_id:id}); setBusy(''); if(error) notify(error.message); else {notify('تم تجديد الإعلان ونشره لمدة أسبوع جديد.');void load();} };
  if(!session)return <main dir="rtl" className="mx-auto max-w-xl px-4 py-20 text-center"><LogIn className="mx-auto text-[#e7663c]"/><h1 className="mt-4 text-2xl font-black">سجّل الدخول لإدارة إعلاناتك</h1><p className="mt-2 text-sm text-slate-500">تابع المراجعة والمبيعات وتجديد الإعلانات من لوحة واحدة.</p><button onClick={()=>setModal('login')} className="mt-6 rounded-xl bg-[#e7663c] px-5 py-3 text-sm font-black text-white">تسجيل الدخول</button></main>;
  return <main dir="rtl" className="mx-auto max-w-[1200px] px-3 py-7 sm:px-6 sm:py-10">
    <div className="mb-7 flex flex-wrap items-center justify-between gap-3"><div><div className="flex items-center gap-2 text-xs font-black text-[#e7663c]"><ShoppingBag size={16}/> مركز البائع</div><h1 className="mt-2 text-2xl font-black text-[#18394c] sm:text-3xl">لوحة إعلاناتي</h1><p className="mt-1 text-sm font-semibold text-slate-400">تحكم كامل في الإعلانات والمراجعة والمبيعات والتجديد.</p></div><div className="flex gap-2"><button onClick={()=>void load()} className="rounded-xl border border-slate-200 bg-white p-3 text-slate-500"><RefreshCw size={17}/></button><button onClick={()=>setModal('sell')} className="flex items-center gap-2 rounded-xl bg-[#e7663c] px-4 py-3 text-xs font-black text-white"><Plus size={16}/> إعلان جديد</button></div></div>
    <div className="mb-6 grid grid-cols-2 gap-3 lg:grid-cols-4">{[['كل الإعلانات',counts.all,ShoppingBag],['قيد المراجعة',counts.pending,Clock3],['منشور',counts.active,CheckCircle2],['مباع',counts.sold,BarChart3]].map(([label,value,Icon])=><div key={String(label)} className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"><span className="grid h-9 w-9 place-items-center rounded-xl bg-slate-50 text-[#e7663c]"><Icon size={18}/></span><b className="mt-3 block text-2xl font-black text-[#18394c]">{value as number}</b><span className="text-xs font-bold text-slate-400">{label as string}</span></div>)}</div>
    {loading?<div className="py-20 text-center text-sm font-bold text-slate-400">جاري تحميل لوحة البائع...</div>:!items.length?<div className="rounded-3xl border border-dashed border-slate-200 bg-white p-14 text-center"><ShoppingBag className="mx-auto text-slate-300" size={36}/><b className="mt-4 block text-lg text-slate-600">ابدأ أول عملية بيع</b><p className="mt-2 text-sm text-slate-400">أضف إعلانك، وبعد المراجعة سيظهر للمشترين.</p><button onClick={()=>setModal('sell')} className="mt-5 rounded-xl bg-[#e7663c] px-5 py-3 text-xs font-black text-white">أضف إعلاناً الآن</button></div>:<div className="grid gap-3">{items.map(item=><article key={item.id} className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"><div className="flex gap-4"><img src={item.image_urls?.[0]||'/hero-eloued.webp'} className="h-24 w-24 shrink-0 rounded-xl object-cover" alt=""/><div className="min-w-0 flex-1"><div className="flex flex-wrap items-start justify-between gap-2"><div><h2 className="font-black text-[#18394c]">{item.title}</h2><p className="mt-1 text-sm font-black text-[#e7663c]">{formatPrice(item.price)} دج</p></div><span className={`rounded-full px-3 py-1.5 text-[10px] font-black ${tone[item.status]}`}>{labels[item.status]}</span></div><div className="mt-3 flex flex-wrap gap-2 text-[11px] font-bold text-slate-400"><span className="flex items-center gap-1"><Eye size={13}/> {item.views_count||0} مشاهدة</span>{item.published_at&&<span>· نُشر {new Date(item.published_at).toLocaleDateString('ar-DZ')}</span>}</div>{item.status==='draft'&&<p className="mt-3 flex items-center gap-1.5 text-xs font-bold text-amber-700"><Clock3 size={14}/> الإعلان قيد مراجعة الإدارة.</p>}{item.status==='archived'&&item.rejection_reason&&<p className="mt-3 rounded-xl bg-rose-50 p-3 text-xs font-bold leading-6 text-rose-700"><XCircle size={14} className="mb-1 inline"/> سبب الرفض: {item.rejection_reason}</p>}{item.status==='active'&&<p className="mt-3 flex items-center gap-1.5 text-xs font-bold text-emerald-700"><CheckCircle2 size={14}/> الإعلان منشور. {canRepublish(item)?'يمكنك الآن تجديده لأسبوع جديد.':'سيظهر زر التجديد بعد 7 أيام من آخر نشر إذا لم يتم بيعه.'}</p>}
      <div className="mt-3 flex flex-wrap gap-2">{item.status==='active'&&<button disabled={busy===item.id} onClick={()=>void changeStatus(item.id,'sold')} className="rounded-lg bg-blue-50 px-3 py-2 text-[11px] font-black text-blue-700">تم البيع</button>}{item.status==='active'&&canRepublish(item)&&<button disabled={busy===item.id} onClick={()=>void republish(item.id)} className="flex items-center gap-1 rounded-lg bg-emerald-50 px-3 py-2 text-[11px] font-black text-emerald-700"><Sparkles size={13}/> إعادة نشر لأسبوع</button>}{item.status!=='archived'&&item.status!=='sold'&&<button disabled={busy===item.id} onClick={()=>void changeStatus(item.id,'archived')} className="flex items-center gap-1 rounded-lg bg-slate-100 px-3 py-2 text-[11px] font-black text-slate-600"><Archive size={13}/> أرشفة</button>}<button onClick={()=>notify('تعديل الإعلان متاح من لوحة الإدارة في هذه النسخة، ويمكن إضافة محرر البائع لاحقاً.')} className="flex items-center gap-1 rounded-lg bg-slate-50 px-3 py-2 text-[11px] font-black text-slate-600"><Edit3 size={13}/> تعديل</button></div>
    </div></div></article>)}</div>}
  </main>;
}
