import { useEffect, useState } from 'react';
import { Archive, CheckCircle2, Clock3, LogIn, RefreshCw, ShoppingBag, XCircle } from 'lucide-react';
import { useNavigate } from 'react-router-dom';
import { useApp } from '../context/AppContext';
import { supabase } from '../lib/supabase';
import { formatPrice } from '../lib/format';

type MyListing = { id:string; title:string; price:number; image_urls?:string[]; status:'draft'|'active'|'sold'|'archived'; rejection_reason?:string|null; created_at:string; published_at?:string|null };
const labels = { draft:'قيد المراجعة', active:'منشور', sold:'مباع', archived:'مؤرشف' } as const;

export function MyListingsPage() {
  const { session, notify, setModal } = useApp(); const navigate = useNavigate();
  const [items,setItems]=useState<MyListing[]>([]); const [loading,setLoading]=useState(true); const [busy,setBusy]=useState('');
  const load=async()=>{ if(!supabase||!session){setLoading(false);return;} setLoading(true); const {data,error}=await supabase.from('listings').select('id,title,price,image_urls,status,rejection_reason,created_at,published_at').eq('seller_id',session.user.id).order('created_at',{ascending:false}); if(error) notify(error.message); else setItems((data||[]) as MyListing[]); setLoading(false); };
  useEffect(()=>{void load();},[session]);
  const changeStatus=async(id:string,status:'sold'|'archived')=>{ if(!supabase||!window.confirm(status==='sold'?'تأكيد أن الإعلان مباع؟':'أرشفة الإعلان؟'))return; setBusy(id); const {error}=await supabase.from('listings').update({status}).eq('id',id); setBusy(''); if(error) notify(error.message); else {notify(status==='sold'?'تم وضع الإعلان كمباع.':'تمت أرشفة الإعلان.');void load();} };
  if(!session)return <main dir="rtl" className="mx-auto max-w-xl px-4 py-20 text-center"><LogIn className="mx-auto text-[#e7663c]"/><h1 className="mt-4 text-2xl font-black">سجّل الدخول لإدارة إعلاناتك</h1><p className="mt-2 text-sm text-slate-500">يمكنك متابعة المراجعة ومعرفة سبب الرفض وحالة كل إعلان.</p><button onClick={()=>setModal('login')} className="mt-6 rounded-xl bg-[#e7663c] px-5 py-3 text-sm font-black text-white">تسجيل الدخول</button></main>;
  return <main dir="rtl" className="mx-auto max-w-[1100px] px-3 py-7 sm:px-6 sm:py-10"><div className="mb-7 flex items-center justify-between gap-3"><div><div className="flex items-center gap-2 text-xs font-black text-[#e7663c]"><ShoppingBag size={16}/> حساب البائع</div><h1 className="mt-2 text-2xl font-black text-[#18394c]">إعلاناتي</h1><p className="mt-1 text-sm font-semibold text-slate-400">كل إعلان يمر بالمراجعة قبل ظهوره للزوار.</p></div><button onClick={()=>void load()} className="rounded-xl border border-slate-200 bg-white p-3 text-slate-500"><RefreshCw size={17}/></button></div>
  {loading?<div className="py-20 text-center text-sm font-bold text-slate-400">جاري تحميل إعلاناتك...</div>:!items.length?<div className="rounded-2xl border border-dashed border-slate-200 bg-white p-12 text-center"><ShoppingBag className="mx-auto text-slate-300"/><b className="mt-3 block text-sm text-slate-600">لا توجد إعلانات بعد</b><button onClick={()=>navigate('/')} className="mt-4 rounded-xl bg-[#e7663c] px-4 py-2 text-xs font-black text-white">العودة وإضافة إعلان</button></div>:<div className="grid gap-3">{items.map(item=><article key={item.id} className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"><div className="flex gap-4"><img src={item.image_urls?.[0]||'/hero-eloued.webp'} className="h-24 w-24 shrink-0 rounded-xl object-cover" alt=""/><div className="min-w-0 flex-1"><div className="flex flex-wrap items-start justify-between gap-2"><div><h2 className="font-black text-[#18394c]">{item.title}</h2><p className="mt-1 text-sm font-black text-[#e7663c]">{formatPrice(item.price)} دج</p></div><span className={`rounded-full px-3 py-1.5 text-[10px] font-black ${item.status==='active'?'bg-emerald-50 text-emerald-700':item.status==='draft'?'bg-amber-50 text-amber-700':'bg-slate-100 text-slate-600'}`}>{labels[item.status]}</span></div>{item.status==='draft'&&<p className="mt-3 flex items-center gap-1.5 text-xs font-bold text-amber-700"><Clock3 size={14}/> الإعلان ينتظر مراجعة الإدارة.</p>}{item.status==='active'&&<p className="mt-3 flex items-center gap-1.5 text-xs font-bold text-emerald-700"><CheckCircle2 size={14}/> الإعلان منشور ويمكن للزوار رؤيته.</p>}{item.status==='archived'&&item.rejection_reason&&<p className="mt-3 rounded-xl bg-rose-50 p-3 text-xs font-bold leading-6 text-rose-700"><XCircle size={14} className="mb-1 inline"/> سبب الرفض: {item.rejection_reason}</p>}<div className="mt-3 flex flex-wrap gap-2">{item.status==='active'&&<button disabled={busy===item.id} onClick={()=>void changeStatus(item.id,'sold')} className="rounded-lg bg-blue-50 px-3 py-2 text-[11px] font-black text-blue-700">وضع كمباع</button>}{item.status!=='archived'&&item.status!=='sold'&&<button disabled={busy===item.id} onClick={()=>void changeStatus(item.id,'archived')} className="flex items-center gap-1 rounded-lg bg-slate-100 px-3 py-2 text-[11px] font-black text-slate-600"><Archive size={13}/> أرشفة</button>}</div></div></div></article>)}</div>}
  </main>;
}
