import { useMemo, useState } from 'react';
import { ArrowLeft, Bell, ChevronLeft, Grid2X2, Heart, Menu, PackagePlus, Plus, Search, ShoppingBag, Sparkles, Tag, UserRound, X } from 'lucide-react';
import { ListingCard, type Listing } from './components/listings/ListingCard';
import { SearchFilters } from './components/listings/SearchFilters';

const municipalities = ['الوادي', 'قمار', 'كوينين', 'البياضة', 'الرباح', 'حاسي خليفة', 'الدبيلة', 'الرقيبة', 'ورماس', 'الطالب العربي'];
const categories = ['الفلاحة والتمور', 'العقارات', 'المركبات والآليات', 'الخدمات والحرف', 'الإلكترونيات', 'المنزل والحديقة'];
const categoryCards = [
  { name: 'الفلاحة والتمور', count: '1,248 إعلان', icon: '🌴', color: 'bg-[#edf4e6]' },
  { name: 'العقارات', count: '864 إعلان', icon: '⌂', color: 'bg-[#fbefe2]' },
  { name: 'المركبات والآليات', count: '632 إعلان', icon: '▣', color: 'bg-[#e9f1f4]' },
  { name: 'الخدمات والحرف', count: '405 إعلان', icon: '✦', color: 'bg-[#f5e9f3]' },
];
const listings: Listing[] = [
  { id: '1', title: 'دقلة نور وادي سوف — نوعية ممتازة', price: 850, image: 'https://images.unsplash.com/photo-1601493700631-2b16ec4b4716?auto=format&fit=crop&w=900&q=80', municipality: 'البياضة', category: 'الفلاحة والتمور', seller: 'مزرعة النخيل', sellerInitials: 'م', verified: true, featured: true, whatsapp: '213550123456', phone: '0550123456', postedAt: 'منذ ساعتين' },
  { id: '2', title: 'شاحنة صغيرة بحالة ممتازة للبيع', price: 1850000, image: 'https://images.unsplash.com/photo-1586191582151-f73872dfd183?auto=format&fit=crop&w=900&q=80', municipality: 'الوادي', category: 'المركبات والآليات', seller: 'عبد القادر', sellerInitials: 'ع', verified: true, whatsapp: '213661987654', phone: '0661987654', postedAt: 'منذ 5 ساعات' },
  { id: '3', title: 'أرض فلاحية 2 هكتار — عقد موثق', price: 4200000, image: 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&w=900&q=80', municipality: 'قمار', category: 'العقارات', seller: 'مكتب سوف العقاري', sellerInitials: 'س', verified: true, whatsapp: '213770246810', phone: '0770246810', postedAt: 'أمس' },
  { id: '4', title: 'تركيب وصيانة مكيفات — خدمة منزلية', price: 1500, image: 'https://images.unsplash.com/photo-1631545806609-6e7f2c6f7c26?auto=format&fit=crop&w=900&q=80', municipality: 'كوينين', category: 'الخدمات والحرف', seller: 'ورشة التبريد', sellerInitials: 'و', whatsapp: '213555333222', phone: '0555333222', postedAt: 'منذ يومين' },
];

export default function App() {
  const [search, setSearch] = useState('');
  const [municipality, setMunicipality] = useState('');
  const [category, setCategory] = useState('');
  const [menuOpen, setMenuOpen] = useState(false);
  const [notice, setNotice] = useState('');
  const filteredListings = useMemo(() => listings.filter((item) => (!search || `${item.title} ${item.seller}`.includes(search)) && (!municipality || item.municipality === municipality) && (!category || item.category === category)), [search, municipality, category]);
  const notify = (message: string) => { setNotice(message); window.setTimeout(() => setNotice(''), 2800); };

  return <div className="min-h-screen bg-[#fcfaf7] text-[#2e3c2b]" dir="rtl">
    <header className="sticky top-0 z-30 border-b border-stone-200/80 bg-[#fcfaf7]/95 backdrop-blur">
      <div className="mx-auto flex h-[72px] max-w-7xl items-center justify-between gap-4 px-4 sm:px-6 lg:px-8">
        <div className="flex items-center gap-3"><button className="rounded-xl p-2 text-stone-600 lg:hidden" onClick={() => setMenuOpen(!menuOpen)}>{menuOpen ? <X /> : <Menu />}</button><div className="grid h-11 w-11 place-items-center rounded-2xl bg-[#2e4a32] text-white shadow-lg shadow-[#2e4a32]/20"><ShoppingBag size={22} /></div><div><p className="text-lg font-black tracking-tight">سوق الوادي</p><p className="text-[10px] font-bold text-[#d8784a]">SOUF MARKET</p></div></div>
        <nav className="hidden items-center gap-7 text-sm font-bold text-stone-500 lg:flex"><a className="text-[#bd6037]" href="#home">الرئيسية</a><a href="#listings" className="transition hover:text-[#bd6037]">تصفح الإعلانات</a><a href="#categories" className="transition hover:text-[#bd6037]">التصنيفات</a><a href="#how" className="transition hover:text-[#bd6037]">كيف يعمل؟</a></nav>
        <div className="flex items-center gap-2"><button aria-label="المفضلة" className="hidden rounded-xl p-2 text-stone-500 hover:bg-stone-100 sm:block" onClick={() => notify('ستظهر إعلاناتك المحفوظة هنا')}><Heart size={19} /></button><button aria-label="الإشعارات" className="hidden rounded-xl p-2 text-stone-500 hover:bg-stone-100 sm:block" onClick={() => notify('لا توجد إشعارات جديدة')}><Bell size={19} /></button><button onClick={() => notify('نموذج إضافة الإعلان جاهز — الخطوة الأولى')} className="flex h-10 items-center gap-2 rounded-xl bg-[#db6b3f] px-3 text-sm font-extrabold text-white shadow-lg shadow-[#db6b3f]/20 transition hover:bg-[#bd6037] active:scale-[0.98]"><Plus size={17} /> <span className="hidden sm:inline">أضف إعلانك</span></button></div>
      </div>{menuOpen && <div className="border-t border-stone-200 bg-white px-5 py-4 lg:hidden"><div className="flex flex-col gap-4 text-sm font-bold text-stone-600"><a href="#home" onClick={() => setMenuOpen(false)}>الرئيسية</a><a href="#listings" onClick={() => setMenuOpen(false)}>تصفح الإعلانات</a><a href="#categories" onClick={() => setMenuOpen(false)}>التصنيفات</a></div></div>}
    </header>
    <main id="home" className="mx-auto max-w-7xl px-4 pb-16 sm:px-6 lg:px-8">
      <section className="relative mt-6 overflow-hidden rounded-[28px] bg-[#2e4a32] px-6 py-12 text-white sm:px-12 sm:py-16"><div className="absolute -left-12 -top-16 h-56 w-56 rounded-full bg-[#8ba66b]/20 blur-2xl" /><div className="absolute -bottom-24 right-1/3 h-64 w-64 rounded-full bg-[#d8784a]/20 blur-3xl" /><div className="relative max-w-2xl"><span className="mb-5 inline-flex items-center gap-2 rounded-full bg-white/10 px-3 py-1.5 text-xs font-bold text-[#f4d693]"><Sparkles size={14} /> للسوق المحلي في ولاية الوادي</span><h1 className="max-w-xl text-3xl font-black leading-[1.3] tracking-tight sm:text-5xl">كل ما تحتاجه، <span className="text-[#f4c95d]">قريب منك.</span></h1><p className="mt-5 max-w-lg text-sm leading-7 text-white/70 sm:text-base">اكتشف آلاف الإعلانات من أهالي الوادي. بيع، اشترِ، وتواصل مباشرة مع البائع بكل سهولة.</p><button onClick={() => document.getElementById('listings')?.scrollIntoView({ behavior: 'smooth' })} className="mt-7 flex items-center gap-2 rounded-xl bg-[#f4c95d] px-5 py-3 text-sm font-black text-[#3b2b16] transition hover:bg-[#f7d77b]">استكشف الإعلانات <ArrowLeft size={17} /></button></div><div className="absolute bottom-0 left-10 hidden h-44 w-44 rounded-t-full border-2 border-white/10 md:block" /></section>
      <section className="relative z-10 -mt-7 mx-3"><SearchFilters search={search} municipality={municipality} category={category} municipalities={municipalities} categories={categories} onSearchChange={setSearch} onMunicipalityChange={setMunicipality} onCategoryChange={setCategory} /></section>
      <section id="categories" className="pt-12"><div className="mb-5 flex items-end justify-between"><div><p className="mb-2 text-xs font-extrabold text-[#d8784a]">تصفح حسب اهتمامك</p><h2 className="text-2xl font-black">التصنيفات الشائعة</h2></div><button className="flex items-center gap-1 text-sm font-bold text-[#bd6037]">كل التصنيفات <ChevronLeft size={16} /></button></div><div className="grid grid-cols-2 gap-3 md:grid-cols-4">{categoryCards.map((item) => <button key={item.name} onClick={() => setCategory(item.name)} className={`flex items-center gap-3 rounded-2xl p-4 text-right transition hover:-translate-y-0.5 hover:shadow-md ${item.color}`}><span className="grid h-12 w-12 shrink-0 place-items-center rounded-xl bg-white/70 text-2xl">{item.icon}</span><span><span className="block text-sm font-black">{item.name}</span><span className="mt-1 block text-xs font-semibold text-stone-500">{item.count}</span></span></button>)}</div></section>
      <section id="listings" className="pt-14"><div className="mb-6 flex items-end justify-between"><div><div className="mb-2 flex items-center gap-2 text-xs font-extrabold text-[#d8784a]"><Tag size={14} /> جديد في السوق</div><h2 className="text-2xl font-black">إعلانات قد تهمك</h2></div><span className="text-sm font-bold text-stone-400">{filteredListings.length} إعلانات</span></div>{filteredListings.length ? <div className="grid gap-5 sm:grid-cols-2 lg:grid-cols-4">{filteredListings.map((listing) => <ListingCard key={listing.id} listing={listing} onContact={(item, method) => notify(method === 'whatsapp' ? `فتح واتساب للتواصل حول «${item.title}»` : `الاتصال بـ ${item.seller}`)} />)}</div> : <div className="rounded-2xl border border-dashed border-stone-300 bg-white p-12 text-center"><Search className="mx-auto mb-3 text-stone-300" size={32} /><p className="font-bold">لا توجد إعلانات بهذه المواصفات</p><button onClick={() => { setSearch(''); setMunicipality(''); setCategory(''); }} className="mt-3 text-sm font-bold text-[#bd6037]">مسح الفلاتر</button></div>}</section>
      <section id="how" className="mt-16 grid gap-5 rounded-[24px] bg-[#f2eadf] p-6 sm:grid-cols-3 sm:p-8"><div><p className="mb-2 text-xs font-extrabold text-[#d8784a]">بسيط وسريع</p><h2 className="text-2xl font-black leading-tight">لماذا سوق الوادي؟</h2><p className="mt-3 text-sm leading-6 text-stone-600">منصة محلية مصممة خصيصاً لاحتياجات أهل سوف.</p></div>{[['01','تواصل مباشر','بدون رسائل معقدة، تواصل مع البائع عبر واتساب أو الهاتف.'],['02','إعلانات محلية','اعثر على ما تبحث عنه في بلديتك وبالقرب منك.']].map(([number,title,text]) => <div key={number} className="rounded-2xl bg-white/70 p-5"><span className="text-3xl font-black text-[#d8784a]/40">{number}</span><h3 className="mt-3 font-black">{title}</h3><p className="mt-2 text-sm leading-6 text-stone-500">{text}</p></div>)}</section>
    </main>
    <footer className="border-t border-stone-200 bg-white"><div className="mx-auto flex max-w-7xl flex-col gap-3 px-4 py-7 text-sm text-stone-500 sm:flex-row sm:items-center sm:justify-between sm:px-6 lg:px-8"><p className="font-bold">© 2026 سوق الوادي — للسوق المحلي في ولاية الوادي</p><div className="flex gap-4"><span>شروط الاستخدام</span><span>تواصل معنا</span></div></div></footer>
    {notice && <div className="fixed bottom-5 left-1/2 z-50 flex -translate-x-1/2 items-center gap-2 rounded-xl bg-[#2e4a32] px-4 py-3 text-sm font-bold text-white shadow-xl"><PackagePlus size={16} /> {notice}</div>}
  </div>;
}
