import { useMemo, useState } from 'react';
import { Bell, ChevronDown, ChevronLeft, Grid2X2, Heart, ListFilter, MapPin, Menu, MessageCircle, Plus, Search, ShoppingBag, SlidersHorizontal, UserRound, X } from 'lucide-react';
import { ListingCard, type Listing } from './components/listings/ListingCard';
import { SearchFilters } from './components/listings/SearchFilters';

const municipalities = ['الوادي', 'قمار', 'كوينين', 'البياضة', 'الرباح', 'حاسي خليفة', 'الدبيلة', 'الرقيبة', 'ورماس', 'الطالب العربي'];
const categories = ['الفلاحة والتمور', 'العقارات', 'المركبات والآليات', 'الخدمات والحرف', 'الإلكترونيات', 'المنزل والحديقة'];
const categoryMenu = [
  ['الفلاحة والتمور', '1,248'], ['العقارات', '864'], ['المركبات والآليات', '632'], ['الخدمات والحرف', '405'], ['الإلكترونيات', '286'], ['المنزل والحديقة', '198'],
];
const listings: Listing[] = [
  { id: '1', title: 'دقلة نور وادي سوف — نوعية ممتازة', price: 850, image: 'https://images.unsplash.com/photo-1601493700631-2b16ec4b4716?auto=format&fit=crop&w=900&q=80', municipality: 'البياضة', category: 'الفلاحة والتمور', seller: 'مزرعة النخيل', sellerInitials: 'م', verified: true, featured: true, whatsapp: '213550123456', phone: '0550123456', postedAt: 'منذ ساعتين' },
  { id: '2', title: 'شاحنة صغيرة بحالة ممتازة للبيع', price: 1850000, image: 'https://images.unsplash.com/photo-1586191582151-f73872dfd183?auto=format&fit=crop&w=900&q=80', municipality: 'الوادي', category: 'المركبات والآليات', seller: 'عبد القادر', sellerInitials: 'ع', verified: true, whatsapp: '213661987654', phone: '0661987654', postedAt: 'منذ 5 ساعات' },
  { id: '3', title: 'أرض فلاحية 2 هكتار — عقد موثق', price: 4200000, image: 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&w=900&q=80', municipality: 'قمار', category: 'العقارات', seller: 'مكتب سوف العقاري', sellerInitials: 'س', verified: true, whatsapp: '213770246810', phone: '0770246810', postedAt: 'أمس' },
  { id: '4', title: 'تركيب وصيانة مكيفات — خدمة منزلية', price: 1500, image: 'https://images.unsplash.com/photo-1631545806609-6e7f2c6f7c26?auto=format&fit=crop&w=900&q=80', municipality: 'كوينين', category: 'الخدمات والحرف', seller: 'ورشة التبريد', sellerInitials: 'و', whatsapp: '213555333222', phone: '0555333222', postedAt: 'منذ يومين' },
  { id: '5', title: 'جرار فلاحي Massey Ferguson', price: 3950000, image: 'https://images.unsplash.com/photo-1592982537447-6f2a6a0a7a7a?auto=format&fit=crop&w=900&q=80', municipality: 'حاسي خليفة', category: 'الفلاحة والتمور', seller: 'خدمات فلاحية سوف', sellerInitials: 'خ', verified: true, whatsapp: '213555888999', phone: '0555888999', postedAt: 'منذ 3 أيام' },
  { id: '6', title: 'هاتف Samsung Galaxy S25 Ultra', price: 185000, image: 'https://images.unsplash.com/photo-1610945265064-0e34e5519bbf?auto=format&fit=crop&w=900&q=80', municipality: 'الوادي', category: 'الإلكترونيات', seller: 'متجر التقنية', sellerInitials: 'ت', verified: true, whatsapp: '213770111222', phone: '0770111222', postedAt: 'منذ 4 أيام' },
];

export default function App() {
  const [search, setSearch] = useState('');
  const [municipality, setMunicipality] = useState('');
  const [category, setCategory] = useState('');
  const [menuOpen, setMenuOpen] = useState(false);
  const [notice, setNotice] = useState('');
  const filteredListings = useMemo(() => listings.filter((item) => (!search || `${item.title} ${item.seller}`.toLowerCase().includes(search.toLowerCase())) && (!municipality || item.municipality === municipality) && (!category || item.category === category)), [search, municipality, category]);
  const notify = (message: string) => { setNotice(message); window.setTimeout(() => setNotice(''), 2600); };
  const reset = () => { setSearch(''); setMunicipality(''); setCategory(''); };

  return <div className="min-h-screen bg-[#f6f7f9] text-[#17212b]" dir="rtl">
    <div className="bg-[#162b3a] text-xs text-white/80"><div className="mx-auto flex h-9 max-w-[1320px] items-center justify-between px-4 sm:px-6 lg:px-8"><span className="hidden sm:inline">سوق الوادي — إعلانات محلية موثوقة</span><div className="flex items-center gap-5"><span>مساعدة</span><span>العربية</span><span className="flex items-center gap-1"><MapPin size={12} /> ولاية الوادي</span></div></div></div>
    <header className="sticky top-0 z-30 border-b border-[#e2e6ea] bg-white shadow-sm"><div className="mx-auto flex h-[74px] max-w-[1320px] items-center gap-4 px-4 sm:px-6 lg:px-8"><button className="rounded-lg p-2 text-slate-500 lg:hidden" onClick={() => setMenuOpen(!menuOpen)}>{menuOpen ? <X /> : <Menu />}</button><a href="#home" className="flex shrink-0 items-center gap-2.5"><span className="grid h-10 w-10 place-items-center rounded-xl bg-[#e8663d] text-white"><ShoppingBag size={21} /></span><span><b className="block text-[18px] leading-5 text-[#162b3a]">سوق الوادي</b><small className="font-bold tracking-[.15em] text-[#e8663d]">SOUF MARKET</small></span></a><div className="hidden h-9 w-px bg-slate-200 lg:block" /><nav className="hidden items-center gap-5 text-sm font-bold text-slate-500 lg:flex"><a className="text-[#e8663d]" href="#home">الرئيسية</a><a href="#listings" className="hover:text-[#e8663d]">الإعلانات</a><a href="#categories" className="hover:text-[#e8663d]">التصنيفات</a></nav><div className="mr-auto flex items-center gap-1"><button className="hidden rounded-lg p-2 text-slate-500 hover:bg-slate-50 sm:block" onClick={() => notify('ستظهر إعلاناتك المحفوظة هنا')}><Heart size={19} /></button><button className="hidden rounded-lg p-2 text-slate-500 hover:bg-slate-50 sm:block" onClick={() => notify('لا توجد إشعارات جديدة')}><Bell size={19} /></button><button className="hidden items-center gap-2 rounded-lg px-3 py-2 text-sm font-bold text-slate-600 hover:bg-slate-50 md:flex" onClick={() => notify('تسجيل الدخول قريباً')}><UserRound size={18} /> دخول</button><button onClick={() => notify('نموذج إضافة الإعلان — الخطوة الأولى')} className="flex h-10 items-center gap-2 rounded-lg bg-[#e8663d] px-3.5 text-sm font-extrabold text-white transition hover:bg-[#cf5732] active:scale-[.98]"><Plus size={17} /> <span>أضف إعلاناً</span></button></div></div>{menuOpen && <div className="border-t border-slate-200 bg-white px-5 py-4 lg:hidden"><div className="flex flex-col gap-4 text-sm font-bold text-slate-600"><a href="#home" onClick={() => setMenuOpen(false)}>الرئيسية</a><a href="#listings" onClick={() => setMenuOpen(false)}>الإعلانات</a><a href="#categories" onClick={() => setMenuOpen(false)}>التصنيفات</a></div></div>}</header>
    <main id="home" className="mx-auto max-w-[1320px] px-4 pb-16 sm:px-6 lg:px-8"><section className="relative mt-5 overflow-hidden rounded-2xl bg-[#203d50] px-6 py-10 sm:px-10"><div className="absolute -left-20 -top-24 h-72 w-72 rounded-full border-[40px] border-[#e8663d]/15" /><div className="absolute bottom-[-100px] left-1/3 h-72 w-72 rounded-full bg-[#efb84a]/10 blur-3xl" /><div className="relative max-w-xl text-white"><p className="mb-3 text-sm font-bold text-[#f6c45b]">منصة البيع والشراء في سوف</p><h1 className="text-3xl font-black leading-tight sm:text-[42px]">ابحث عن أي شيء<br /><span className="text-[#f6c45b]">بالقرب منك</span></h1><p className="mt-4 text-sm leading-7 text-white/70">إعلانات موثوقة من الوادي وبلدياتها، بتواصل مباشر وسريع مع البائع.</p></div><div className="absolute bottom-0 left-12 hidden gap-2 opacity-20 md:flex"><span className="h-28 w-16 rounded-t-full border-2 border-white" /><span className="h-20 w-16 rounded-t-full border-2 border-white" /><span className="h-36 w-16 rounded-t-full border-2 border-white" /></div></section>
      <section className="relative z-10 -mt-6 mx-2"><SearchFilters search={search} municipality={municipality} category={category} municipalities={municipalities} categories={categories} onSearchChange={setSearch} onMunicipalityChange={setMunicipality} onCategoryChange={setCategory} /></section>
      <div className="mt-9 grid gap-8 lg:grid-cols-[245px_1fr]"><aside id="categories" className="hidden lg:block"><div className="rounded-xl border border-[#e1e5e8] bg-white p-4"><div className="mb-4 flex items-center justify-between border-b border-slate-100 pb-4"><h2 className="font-black">التصنيفات</h2><Grid2X2 size={18} className="text-[#e8663d]" /></div><div className="space-y-1">{categoryMenu.map(([name, count]) => <button key={name} onClick={() => setCategory(name)} className={`flex w-full items-center justify-between rounded-lg px-3 py-3 text-right text-sm font-bold transition ${category === name ? 'bg-[#fff0eb] text-[#d95431]' : 'text-slate-600 hover:bg-slate-50'}`}><span>{name}</span><span className="text-xs font-semibold text-slate-400">{count}</span></button>)}</div><button onClick={() => setCategory('')} className="mt-3 flex items-center gap-1 px-3 text-xs font-bold text-[#e8663d]">كل التصنيفات <ChevronLeft size={14} /></button></div><div className="mt-4 rounded-xl bg-[#eaf2f5] p-5"><MessageCircle className="mb-3 text-[#287f72]" size={22} /><h3 className="font-black">تواصل بأمان</h3><p className="mt-2 text-xs leading-6 text-slate-600">لا ترسل أموالاً قبل معاينة السلعة والتأكد من البائع.</p></div></aside><section id="listings" className="min-w-0"><div className="mb-5 flex flex-wrap items-end justify-between gap-3"><div><div className="mb-2 flex items-center gap-2 text-xs font-black text-[#e8663d]"><span className="h-2 w-2 rounded-full bg-[#e8663d]" /> أحدث الإعلانات</div><h2 className="text-2xl font-black">إعلانات قد تهمك</h2></div><div className="flex items-center gap-2"><button className="hidden items-center gap-2 rounded-lg border border-slate-200 bg-white px-3 py-2 text-xs font-bold text-slate-600 sm:flex"><SlidersHorizontal size={15} /> ترتيب: الأحدث <ChevronDown size={14} /></button><span className="text-xs font-bold text-slate-400">{filteredListings.length} إعلانات</span></div></div>{filteredListings.length ? <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{filteredListings.map((listing) => <ListingCard key={listing.id} listing={listing} onContact={(item, method) => notify(method === 'whatsapp' ? `فتح واتساب حول «${item.title}»` : `الاتصال بـ ${item.seller}`)} />)}</div> : <div className="rounded-xl border border-dashed border-slate-300 bg-white p-14 text-center"><ListFilter className="mx-auto mb-3 text-slate-300" size={32} /><p className="font-bold">لم نجد إعلانات مطابقة</p><button onClick={reset} className="mt-3 text-sm font-bold text-[#e8663d]">مسح الفلاتر</button></div>}</section></div>
      <section className="mt-12 border-t border-slate-200 pt-8"><div className="mb-5 flex items-center justify-between"><div><p className="mb-1 text-xs font-black text-[#e8663d]">استكشف أكثر</p><h2 className="text-xl font-black">تسوق حسب البلدية</h2></div><button className="text-sm font-bold text-[#e8663d]">عرض الكل</button></div><div className="flex flex-wrap gap-2">{municipalities.slice(0, 8).map((place) => <button key={place} onClick={() => setMunicipality(place)} className="rounded-full border border-slate-200 bg-white px-4 py-2 text-sm font-bold text-slate-600 transition hover:border-[#e8663d] hover:text-[#e8663d]">{place}</button>)}</div></section>
    </main><footer className="border-t border-slate-200 bg-white"><div className="mx-auto flex max-w-[1320px] flex-col gap-3 px-4 py-7 text-sm text-slate-500 sm:flex-row sm:items-center sm:justify-between sm:px-6 lg:px-8"><b className="text-[#162b3a]">سوق الوادي</b><span>منصة محلية لأهالي ولاية الوادي © 2026</span><span>شروط الاستخدام · تواصل معنا</span></div></footer>{notice && <div className="fixed bottom-5 left-1/2 z-50 flex -translate-x-1/2 items-center gap-2 whitespace-nowrap rounded-lg bg-[#162b3a] px-4 py-3 text-sm font-bold text-white shadow-xl"><MessageCircle size={16} /> {notice}</div>}
  </div>;
}
