import { useMemo, useState } from 'react';
import { Bell, ChevronDown, ChevronLeft, Grid2X2, Heart, Home, ListFilter, MapPin, Menu, MessageCircle, Plus, Search, ShoppingBag, SlidersHorizontal, UserRound, X } from 'lucide-react';
import { ListingCard, type Listing } from './components/listings/ListingCard';
import { SearchFilters } from './components/listings/SearchFilters';

const municipalities = ['الوادي', 'قمار', 'كوينين', 'البياضة', 'الرباح', 'حاسي خليفة', 'الدبيلة', 'الرقيبة', 'ورماس', 'الطالب العربي'];
const categories = ['الفلاحة والتمور', 'العقارات', 'المركبات والآليات', 'الخدمات والحرف', 'الإلكترونيات', 'المنزل والحديقة'];
const categoriesMeta = [
  { name: 'الفلاحة والتمور', count: '1,248', icon: '🌴' }, { name: 'العقارات', count: '864', icon: '⌂' }, { name: 'المركبات والآليات', count: '632', icon: '▣' }, { name: 'الخدمات والحرف', count: '405', icon: '✦' }, { name: 'الإلكترونيات', count: '286', icon: '▤' }, { name: 'المنزل والحديقة', count: '198', icon: '⌂' },
];
const listings: Listing[] = [
  { id: '1', title: 'دقلة نور وادي سوف — نوعية ممتازة', price: 850, image: 'https://images.unsplash.com/photo-1601493700631-2b16ec4b4716?auto=format&fit=crop&w=900&q=80', municipality: 'البياضة', category: 'الفلاحة والتمور', seller: 'مزرعة النخيل', sellerInitials: 'م', verified: true, featured: true, whatsapp: '213550123456', phone: '0550123456', postedAt: 'منذ ساعتين' },
  { id: '2', title: 'شاحنة صغيرة بحالة ممتازة للبيع', price: 1850000, image: 'https://images.unsplash.com/photo-1586191582151-f73872dfd183?auto=format&fit=crop&w=900&q=80', municipality: 'الوادي', category: 'المركبات والآليات', seller: 'عبد القادر', sellerInitials: 'ع', verified: true, whatsapp: '213661987654', phone: '0661987654', postedAt: 'منذ 5 ساعات' },
  { id: '3', title: 'أرض فلاحية 2 هكتار — عقد موثق', price: 4200000, image: 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&w=900&q=80', municipality: 'قمار', category: 'العقارات', seller: 'مكتب سوف العقاري', sellerInitials: 'س', verified: true, whatsapp: '213770246810', phone: '0770246810', postedAt: 'أمس' },
  { id: '4', title: 'تركيب وصيانة مكيفات — خدمة منزلية', price: 1500, image: 'https://images.unsplash.com/photo-1631545806609-6e7f2c6f7c26?auto=format&fit=crop&w=900&q=80', municipality: 'كوينين', category: 'الخدمات والحرف', seller: 'ورشة التبريد', sellerInitials: 'و', whatsapp: '213555333222', phone: '0555333222', postedAt: 'منذ يومين' },
  { id: '5', title: 'جرار فلاحي Massey Ferguson', price: 3950000, image: 'https://images.unsplash.com/photo-1592982537447-6f2a6a0a7a7a?auto=format&fit=crop&w=900&q=80', municipality: 'حاسي خليفة', category: 'الفلاحة والتمور', seller: 'خدمات فلاحية سوف', sellerInitials: 'خ', verified: true, whatsapp: '213555888999', phone: '0555888999', postedAt: 'منذ 3 أيام' },
  { id: '6', title: 'هاتف Samsung Galaxy S25 Ultra', price: 185000, image: 'https://images.unsplash.com/photo-1610945265064-0e34e5519bbf?auto=format&fit=crop&w=900&q=80', municipality: 'الوادي', category: 'الإلكترونيات', seller: 'متجر التقنية', sellerInitials: 'ت', verified: true, whatsapp: '213770111222', phone: '0770111222', postedAt: 'منذ 4 أيام' },
];

export default function App() {
  const [search, setSearch] = useState(''); const [municipality, setMunicipality] = useState(''); const [category, setCategory] = useState(''); const [menuOpen, setMenuOpen] = useState(false); const [notice, setNotice] = useState('');
  const filteredListings = useMemo(() => listings.filter((item) => (!search || `${item.title} ${item.seller}`.toLowerCase().includes(search.toLowerCase())) && (!municipality || item.municipality === municipality) && (!category || item.category === category)), [search, municipality, category]);
  const notify = (message: string) => { setNotice(message); window.setTimeout(() => setNotice(''), 2600); };
  const reset = () => { setSearch(''); setMunicipality(''); setCategory(''); };
  const scrollTo = (id: string) => document.getElementById(id)?.scrollIntoView({ behavior: 'smooth', block: 'start' });

  return <div className="min-h-screen bg-[#f5f6f8] pb-16 text-[#17212b] md:pb-0" dir="rtl">
    <div className="hidden bg-[#152c3c] text-xs text-white/80 md:block"><div className="mx-auto flex h-9 max-w-[1320px] items-center justify-between px-4 sm:px-6 lg:px-8"><span>منصة الإعلانات المحلية في ولاية الوادي</span><div className="flex items-center gap-5"><span>مساعدة</span><span>العربية</span><span className="flex items-center gap-1"><MapPin size={12} /> الوادي</span></div></div></div>
    <header className="sticky top-0 z-40 border-b border-slate-200 bg-white shadow-sm"><div className="mx-auto flex h-[62px] max-w-[1320px] items-center gap-2.5 px-3 sm:h-[72px] sm:px-6 lg:px-8"><button aria-label="فتح القائمة" className="rounded-lg p-2 text-slate-500 lg:hidden" onClick={() => setMenuOpen(!menuOpen)}>{menuOpen ? <X size={21} /> : <Menu size={21} />}</button><a href="#home" className="flex shrink-0 items-center gap-2"><span className="grid h-9 w-9 place-items-center rounded-lg bg-[#e7663c] text-white sm:h-10 sm:w-10"><ShoppingBag size={19} /></span><span><b className="block text-[16px] leading-5 text-[#152c3c] sm:text-[18px]">سوق الوادي</b><small className="hidden font-bold tracking-[.14em] text-[#e7663c] sm:block">SOUF MARKET</small></span></a><nav className="hidden items-center gap-6 text-sm font-bold text-slate-500 lg:flex lg:mr-8"><a className="text-[#e7663c]" href="#home">الرئيسية</a><a href="#listings" className="hover:text-[#e7663c]">الإعلانات</a><a href="#categories" className="hover:text-[#e7663c]">التصنيفات</a></nav><div className="mr-auto flex items-center gap-0.5 sm:gap-1"><button aria-label="المفضلة" className="hidden rounded-lg p-2 text-slate-500 hover:bg-slate-50 sm:block" onClick={() => notify('ستظهر إعلاناتك المحفوظة هنا')}><Heart size={19} /></button><button aria-label="الإشعارات" className="hidden rounded-lg p-2 text-slate-500 hover:bg-slate-50 sm:block" onClick={() => notify('لا توجد إشعارات جديدة')}><Bell size={19} /></button><button onClick={() => notify('تسجيل الدخول قريباً')} className="hidden items-center gap-1.5 rounded-lg px-2.5 py-2 text-sm font-bold text-slate-600 hover:bg-slate-50 md:flex"><UserRound size={17} /> دخول</button><button onClick={() => notify('نموذج إضافة الإعلان — الخطوة الأولى')} className="flex h-9 items-center gap-1.5 rounded-lg bg-[#e7663c] px-2.5 text-xs font-extrabold text-white transition hover:bg-[#ce5732] sm:h-10 sm:px-3.5 sm:text-sm"><Plus size={16} /> <span>أضف إعلاناً</span></button></div></div>{menuOpen && <div className="border-t border-slate-200 bg-white px-5 py-4 lg:hidden"><div className="flex flex-col gap-4 text-sm font-bold text-slate-600"><a href="#home" onClick={() => setMenuOpen(false)}>الرئيسية</a><a href="#listings" onClick={() => setMenuOpen(false)}>الإعلانات</a><a href="#categories" onClick={() => setMenuOpen(false)}>التصنيفات</a></div></div>}</header>
    <main id="home" className="mx-auto max-w-[1320px] px-3 pb-10 sm:px-6 lg:px-8"><section className="relative mt-3 overflow-hidden rounded-xl bg-[#203f53] px-5 py-7 sm:mt-5 sm:rounded-2xl sm:px-10 sm:py-11"><div className="absolute -left-20 -top-24 h-72 w-72 rounded-full border-[36px] border-[#e7663c]/15" /><div className="absolute bottom-[-100px] left-1/3 h-72 w-72 rounded-full bg-[#f3bd50]/10 blur-3xl" /><div className="relative max-w-xl text-white"><p className="mb-2 text-xs font-bold text-[#f5c65b] sm:text-sm">منصة البيع والشراء في سوف</p><h1 className="text-[28px] font-black leading-[1.35] sm:text-[42px]">كل ما تحتاجه<br /><span className="text-[#f5c65b]">بالقرب منك</span></h1><p className="mt-3 max-w-md text-xs leading-6 text-white/70 sm:mt-4 sm:text-sm sm:leading-7">إعلانات موثوقة من الوادي وبلدياتها، بتواصل مباشر وسريع مع البائع.</p></div></section>
      <section className="relative z-10 -mt-4 mx-1 sm:-mt-6 sm:mx-2"><SearchFilters search={search} municipality={municipality} category={category} municipalities={municipalities} categories={categories} onSearchChange={setSearch} onMunicipalityChange={setMunicipality} onCategoryChange={setCategory} /></section>
      <section id="categories" className="mt-7 scroll-mt-20"><div className="mb-3 flex items-center justify-between"><h2 className="text-lg font-black sm:text-xl">التصنيفات</h2><button onClick={() => notify('كل التصنيفات قريباً')} className="flex items-center gap-1 text-xs font-bold text-[#e7663c]">عرض الكل <ChevronLeft size={14} /></button></div><div className="-mx-3 flex snap-x gap-2.5 overflow-x-auto px-3 pb-2 scrollbar-none sm:mx-0 sm:grid sm:grid-cols-3 sm:gap-3 sm:px-0 lg:grid-cols-6">{categoriesMeta.map((item) => <button key={item.name} onClick={() => setCategory(item.name)} className={`flex min-w-[142px] snap-start items-center gap-2.5 rounded-xl border p-3 text-right transition sm:min-w-0 sm:flex-col sm:items-start sm:p-4 ${category === item.name ? 'border-[#f2a78e] bg-[#fff1ec]' : 'border-slate-200 bg-white hover:border-[#f2a78e]'}`}><span className="grid h-10 w-10 shrink-0 place-items-center rounded-lg bg-[#f7f8fa] text-xl sm:h-11 sm:w-11">{item.icon}</span><span><b className="block text-xs font-black leading-5 sm:text-sm">{item.name}</b><small className="mt-0.5 block text-[10px] font-bold text-slate-400">{item.count} إعلان</small></span></button>)}</div></section>
      <div className="mt-8 grid gap-8 lg:grid-cols-[225px_1fr]"><aside className="hidden lg:block"><div className="rounded-xl border border-slate-200 bg-white p-4"><div className="mb-3 flex items-center justify-between border-b border-slate-100 pb-3"><h2 className="font-black">تصفح سريع</h2><Grid2X2 size={17} className="text-[#e7663c]" /></div><div className="space-y-1">{categories.map((item) => <button key={item} onClick={() => setCategory(item)} className={`flex w-full items-center justify-between rounded-lg px-2.5 py-2.5 text-right text-xs font-bold ${category === item ? 'bg-[#fff1ec] text-[#d65230]' : 'text-slate-600 hover:bg-slate-50'}`}>{item}<ChevronLeft size={14} className="text-slate-300" /></button>)}</div></div><div className="mt-4 rounded-xl bg-[#eaf2f5] p-4"><MessageCircle className="mb-2 text-[#287f72]" size={21} /><h3 className="text-sm font-black">تواصل بأمان</h3><p className="mt-1 text-[11px] leading-5 text-slate-600">عاين السلعة وتأكد من البائع قبل الدفع.</p></div></aside><section id="listings" className="min-w-0 scroll-mt-20"><div className="mb-4 flex items-end justify-between gap-2"><div><div className="mb-1.5 flex items-center gap-1.5 text-[11px] font-black text-[#e7663c]"><span className="h-1.5 w-1.5 rounded-full bg-[#e7663c]" /> الأحدث في السوق</div><h2 className="text-xl font-black sm:text-2xl">إعلانات قد تهمك</h2></div><div className="flex items-center gap-2"><button className="hidden items-center gap-1.5 rounded-lg border border-slate-200 bg-white px-3 py-2 text-[11px] font-bold text-slate-600 sm:flex"><SlidersHorizontal size={14} /> الأحدث <ChevronDown size={13} /></button><span className="text-[11px] font-bold text-slate-400">{filteredListings.length} إعلانات</span></div></div>{filteredListings.length ? <div className="grid grid-cols-2 gap-2.5 sm:gap-4 md:grid-cols-3">{filteredListings.map((listing) => <ListingCard key={listing.id} listing={listing} onContact={(item, method) => notify(method === 'whatsapp' ? `فتح واتساب حول «${item.title}»` : `الاتصال بـ ${item.seller}`)} />)}</div> : <div className="rounded-xl border border-dashed border-slate-300 bg-white p-12 text-center"><ListFilter className="mx-auto mb-3 text-slate-300" size={30} /><p className="text-sm font-bold">لم نجد إعلانات مطابقة</p><button onClick={reset} className="mt-3 text-xs font-bold text-[#e7663c]">مسح الفلاتر</button></div>}</section></div>
      <section className="mt-9 border-t border-slate-200 pt-7"><div className="mb-3 flex items-center justify-between"><h2 className="text-lg font-black">تصفح حسب البلدية</h2><MapPin size={18} className="text-[#e7663c]" /></div><div className="flex gap-2 overflow-x-auto pb-2 scrollbar-none">{municipalities.slice(0, 8).map((place) => <button key={place} onClick={() => setMunicipality(place)} className="shrink-0 rounded-full border border-slate-200 bg-white px-3.5 py-2 text-xs font-bold text-slate-600 transition hover:border-[#e7663c] hover:text-[#e7663c]">{place}</button>)}</div></section>
    </main><footer className="hidden border-t border-slate-200 bg-white md:block"><div className="mx-auto flex max-w-[1320px] items-center justify-between px-4 py-7 text-sm text-slate-500 sm:px-6 lg:px-8"><b className="text-[#152c3c]">سوق الوادي</b><span>منصة محلية لأهالي ولاية الوادي © 2026</span><span>شروط الاستخدام · تواصل معنا</span></div></footer><nav className="fixed inset-x-0 bottom-0 z-40 grid h-[60px] grid-cols-4 border-t border-slate-200 bg-white/95 shadow-[0_-4px_18px_rgba(21,42,57,.08)] backdrop-blur md:hidden"><button onClick={() => scrollTo('home')} className="flex flex-col items-center justify-center gap-0.5 text-[#e7663c]"><Home size={19} /><span className="text-[10px] font-bold">الرئيسية</span></button><button onClick={() => scrollTo('categories')} className="flex flex-col items-center justify-center gap-0.5 text-slate-500"><Grid2X2 size={19} /><span className="text-[10px] font-bold">التصنيفات</span></button><button onClick={() => notify('تسجيل الدخول لإدارة إعلاناتك')} className="flex flex-col items-center justify-center gap-0.5 text-slate-500"><Heart size={19} /><span className="text-[10px] font-bold">المفضلة</span></button><button onClick={() => notify('تسجيل الدخول قريباً')} className="flex flex-col items-center justify-center gap-0.5 text-slate-500"><UserRound size={19} /><span className="text-[10px] font-bold">حسابي</span></button></nav>{notice && <div className="fixed bottom-[72px] left-1/2 z-50 flex -translate-x-1/2 items-center gap-2 whitespace-nowrap rounded-lg bg-[#152c3c] px-3.5 py-2.5 text-xs font-bold text-white shadow-xl md:bottom-5"><MessageCircle size={15} /> {notice}</div>}
  </div>;
}
