import type { ComponentProps } from 'react';
import { Heart, MapPin, MessageCircle, Phone, ShieldCheck } from 'lucide-react';

export type Listing = { id: string; title: string; price: number; image: string; municipality: string; category: string; seller: string; sellerInitials: string; verified?: boolean; featured?: boolean; whatsapp: string; phone: string; postedAt: string };
type ListingCardProps = ComponentProps<'article'> & { listing: Listing; onContact?: (listing: Listing, method: 'whatsapp' | 'phone') => void };
export function formatPrice(price: number) { return new Intl.NumberFormat('ar-DZ').format(price); }

export function ListingCard({ listing, onContact }: ListingCardProps) {
  const whatsappUrl = `https://wa.me/${listing.whatsapp.replace(/[^0-9]/g, '')}?text=${encodeURIComponent(`السلام عليكم، أستفسر عن: ${listing.title}`)}`;
  return <article className="group overflow-hidden rounded-xl border border-[#e0e4e7] bg-white shadow-[0_3px_12px_rgba(21,42,57,.04)] transition duration-200 hover:-translate-y-0.5 hover:border-[#f0b5a2] hover:shadow-[0_10px_25px_rgba(21,42,57,.10)]"><div className="relative aspect-[1.22] overflow-hidden bg-slate-100"><img src={listing.image} alt={listing.title} loading="lazy" className="h-full w-full object-cover transition duration-500 group-hover:scale-105" /><div className="absolute inset-x-3 top-3 flex items-center justify-between">{listing.featured ? <span className="rounded-md bg-[#f6c45b] px-2.5 py-1 text-[10px] font-black text-[#5c4218]">مميز</span> : <span /> }<button aria-label="حفظ الإعلان" className="grid h-8 w-8 place-items-center rounded-full bg-white/95 text-slate-500 shadow-sm transition hover:text-[#e8663d]"><Heart size={15} /></button></div></div><div className="p-3.5"><h3 className="line-clamp-2 min-h-[48px] text-[15px] font-extrabold leading-6 text-[#1b2b36]">{listing.title}</h3><p className="mt-2 text-lg font-black text-[#e15f39]">{formatPrice(listing.price)} <span className="text-xs font-bold">دج</span></p><div className="mt-2.5 flex items-center justify-between text-[11px] text-slate-400"><span className="flex items-center gap-1 font-bold"><MapPin size={13} className="text-[#e8663d]" /> {listing.municipality}</span><span>{listing.postedAt}</span></div><div className="mt-3 flex items-center gap-2 border-t border-slate-100 pt-3"><span className="grid h-7 w-7 place-items-center rounded-full bg-[#eaf2f5] text-[10px] font-black text-[#287f72]">{listing.sellerInitials}</span><span className="truncate text-xs font-bold text-slate-600">{listing.seller}</span>{listing.verified && <ShieldCheck size={14} className="shrink-0 text-[#287f72]" />}</div><div className="mt-3 grid grid-cols-[1fr_auto] gap-2"><a href={whatsappUrl} target="_blank" rel="noreferrer" onClick={() => onContact?.(listing, 'whatsapp')} className="flex h-10 items-center justify-center gap-1.5 rounded-lg bg-[#287f72] text-xs font-extrabold text-white transition hover:bg-[#216a60] active:scale-[.98]"><MessageCircle size={15} /> واتساب</a><a href={`tel:${listing.phone}`} onClick={() => onContact?.(listing, 'phone')} aria-label="اتصال هاتفي" className="grid h-10 w-11 place-items-center rounded-lg border border-slate-200 bg-slate-50 text-[#287f72] transition hover:bg-[#eaf2f5] active:scale-[.98]"><Phone size={15} /></a></div></div></article>;
}
